### ISSUE TITLE
Support for repeated query parameters

### ISSUE THREAD

**Issue by wearpants** [marshmallow-code/webargs#1]
It'd be helpful to support multiple values for the same query parameter, like Flask-RESTful. These would be accumulated into a list, after validation.

http://flask-restful.readthedocs.org/en/latest/reqparse.html#multiple-values-lists

**Comment by sloria** [comment]
Added. You can now do:

``` python
my_args = {
    'name': Arg(list, multiple=True)
}
```

Thanks for the suggestion.

**Comment by wearpants** [comment]
Hmm, is the type specifier really intended to be `list` here?
Reqparse/argparse take a basic type (int, etc) in this situation and use a
`multiple`-like flag to indicate that the arg is a list of basic types.
That way you still get type conversion on each element...

**Comment by sloria** [comment]
Yes, I think the approach you're describing makes more sense. I will change
later today or tomorrow when I'm off work.

---

StevenLoria.com

**Comment by sloria** [comment]
Fixed. Thanks again!
