### ISSUE TITLE
what do i do if a field's value is necessary for validating another field?

### ISSUE THREAD

**Issue by boobby** [marshmallow-code/webargs#10]
I think django's  form validation is a good solution , but it is too heavy.

**Comment by sloria** [comment]
I've just added a `validate` parameter to the `Parser.parse` method (which you can also pass to `use_args` and `use_kwargs`). It allows you to pass a callable that receives the full arguments dictionary as its only argument.

Example:

``` python
from webargs import Arg
from webargs.flaskparser import parser

args = {
    'age': Arg(int),
    'years_employed': Arg(int),
}

# ...
result = parser.parse(args, validate=lambda args: args['years_employed'] < args['age'])
```

Does this solve your problem?

**Comment by timfeirg** [comment]
Consider adding support to a `pass_original` flag? Just like marshmallow's `validates_schema` method (see http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.decorators.validates_schema)

**Comment by timfeirg** [comment]
sorry, I've seen the examples from https://github.com/sloria/webargs/issues/146, and I realized I should probably just use marshmallow schema with webargs.

**Comment by sloria** [comment]
@timfeirg Correct. A marshmallow `Schema` and `@validates_schema` should meet your use case.
