### ISSUE TITLE
Using 'use_kwargs' with a callable

### ISSUE THREAD

**Issue by ksesong** [marshmallow-code/webargs#103]
When we use the `use_kwargs` method with a callable (that accepts a `request` and returns a `Schema` instance), [like in this example with `use_kwargs`](http://webargs.readthedocs.org/en/latest/advanced.html#reducing-boilerplate): an error raises [here](https://github.com/sloria/webargs/blob/dev/webargs/core.py#L360), as the `argmap` is now a `callable`, not a `dict`.

```
argmap = <function factory at 0x1090227d0>

    def get_field_names_for_argmap(argmap):
        if isinstance(argmap, ma.Schema):
            all_field_names = set([fname for fname, fobj in iteritems(argmap.fields)
                if not fobj.dump_only])
        else:
>           all_field_names = set(argmap.keys())
E           AttributeError: 'function' object has no attribute 'keys'
```

`get_field_names_for_argmap` is called by `fill_in_missing_args`.

**Comment by sloria** [comment]
Thanks for reporting. I've released a hotfix for this.
