### ISSUE TITLE
webargs with Django REST Framework

### ISSUE THREAD

**Issue by claytonbonelli** [marshmallow-code/webargs#106]
Hi,

I'm trying to use the webargs with the Django Rest Framework and I have failled.

Please, see my code:

from webargs import fields
from webargs.djangoparser import use_args
from rest_framework.views import APIView

purchase_args = {
    'test': fields.Str(required=True),
}

class AnimalGroupPurchase(APIView):

```
@use_args(purchase_args)
def post(self, request, args):
    pass
```

From my browser I sent a POST with a JSON, but I got the following error message

"RawPostDataException: You cannot access body after reading from request's data stream"

Could you help me please?

Clayton

**Comment by sloria** [comment]
I think you're getting that error because DRF reads the JSON request body and puts it into `request.data`.

You can add a [custom location handler](http://webargs.readthedocs.io/en/latest/advanced.html#custom-location-handlers) for `request.data`.

``` python
import functools 

from webargs import core
from webargs.djangoparser import parser

@parser.location_handler('data')
def parse_data(request, name, field):
    return core.get_value(request.data, name, field)

# Parse 'data' and querystring by default
use_args = functools.partial(parser.use_args, locations=('data', 'query', ))
```
