### ISSUE TITLE
Is there a way to differentiate exposed and internal field names?

### ISSUE THREAD

**Issue by JivanRoquet** [marshmallow-code/webargs#108]
Hi,

The JSON-API specification imposes a hyphens-delimited writing style for querying additional filters like:

```
api.com/posts?author-id=123&is-published=true
```

The specification actually says that there **must be** at least one hyphen in each field name, so a pretty common solution is to make all one-word fields begin by `is-` (like in `is-published`, `is-deleted`...).

However, those fields are very likely to be named in a different way in the database implementation.

So let's say that one has to expose the following field names in queryString parameters:
- `author-id`
- `is-published`
- `is-deleted`
- `created-at`

Whereas in the database, those fields are respectively:
- `author_id`
- `published`
- `deleted`
- `created_at`

Is there a way (and if not, wouldn't it be nice) to manage this directly in **webargs**? Currently, I have to write a routine to remove all `^is-` and convert `-` to `_` for each field name and it appears clunky, especially since `args` are not passed via `**kwargs` but with positional arguments (this makes it harder to predict webargs' stuff index in each view handler's `*args`, when trying to put this routine in a decorator).

If not implemented, could this feature take the form of an additional `exposed` parameter for each field? Something like:

``` python
args = {
    'author_id': fields.Str(exposed='author-id'),
    'published': fields.Boolean(exposed='is-published'),
    'deleted': fields.Boolean(exposed='is-deleted'),
    'created_at': fields.Integer(exposed='created-at')
}
```

**Comment by sloria** [comment]
Yes; try the `load_from` parameter.

**Comment by JivanRoquet** [comment]
That is awesome, thanks. My bad from missing it in the "Basic Usage" section of the docs.
