### ISSUE TITLE
Error message is unhelpful for List fields with OneOf requirements

### ISSUE THREAD

**Issue by dswhite42** [marshmallow-code/webargs#111]
I want to accept multiple values for "units", but I want them to be limited to certain values (minutes, days, hours, years).  But given this:

`args = {'units': fields.List(fields.Str(validate=validate.OneOf(['minutes', 'days', 'hours', 'years'])))}`

and this URL:

`http://localhost/test?units=days&units=hours&units=years&units=foobar`

the error message looks like this:

```
{
    "errors": {
        "units": {
            "3": [
                "Not a valid choice."
            ]
        }
    },
}
```

Can the error message show the wrong value (foobar) rather than show the index of the wrong entry (3)?

**Comment by sloria** [comment]
The error message for the `OneOf` validator can be customized with the `error` argument:

``` python
args = {'units': fields.List(fields.Str(validate=validate.OneOf(['minutes', 'days', 'hours', 'years'], error='{input} is not a valid unit')))}
```

See http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.validate.OneOf .

Does that meet your use case?

**Comment by dswhite42** [comment]
I think it does.  It would still be handy if the dict of error messages had the field name as the key rather than the list index.  (That way `http://localhost:5001/test?units=eons&units=eons&units=eons` would only produce a single error message with the key "eons" instead of three errors for index 0, 1, 2)  But that's minor.  I think your solution will be fine for what I need.  Thanks for the pointer.

**Comment by sloria** [comment]
OK, closing this for now. Feel free to report any improvements to the error handling in the marshmallow github issue tracker.
