### ISSUE TITLE
How to validate dynamic keys from JSON

### ISSUE THREAD

**Issue by brijeshb42** [marshmallow-code/webargs#114]
In my use case, in different requests, the keys in the json will be different.
For ex:
Request 1:

``` json
{
    "thumbnail": { "x": 1, "y": 1, "width": 100, "height": 100 }
}
```

Request 2:

``` json
{
    "wide": { "x": 1, "y": 1, "width": 1000, "height": 400 }
}
```

The structure of key's value will be same, but key names will be different.

How do I first validate that the key name itself first is a String, and then validate the value dictionary?

**Comment by alexpantyukhin** [comment]
Hi!

I think that this question is more suitable for this https://github.com/marshmallow-code/marshmallow repo.

As for me I would create some class with base `Dict` class https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L1030  and implement similar logic like it's done in the `List` class https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L477 .
