### ISSUE TITLE
compatibility with chalice

### ISSUE THREAD

**Issue by zwing99** [marshmallow-code/webargs#115]
I know this feels like "hot of the press" requesting. But it seems it would be not that hard to allow this to integrate with AWS's new chalice micro framework. See: https://github.com/awslabs/chalice and https://aws.amazon.com/blogs/developer/preview-the-python-serverless-microframework-for-aws/ .

I can imagine many users wanting this.

**Comment by sloria** [comment]
Thanks for the suggestion. It does look like it would be straightforward to integrate chalice with webargs.

I think an initial iteration would best be implemented as a separate library (i.e. `webargs-chalice`), at least while chalice is in an alpha state.

**Comment by jeffglover** [comment]
I don't know if it's worth reopening this, but chalice is no longer alpha and this would be a useful feature. I'd be willing to contribute back and issue a pull request if desired.

**Comment by zwing99** [comment]
Agree. I think we should reopen this issue.

**Comment by sloria** [comment]
I still propose that the chalice parser be implemented as a separate package. We've put a halt on adding new parsers in order to reduce maintenance burden. I've just made a new "Ecosystem" page in the Wiki. If someone ends up publishing "webargs-chalice", please add it to that page.

**Comment by jeffglover** [comment]
Ok, I'll look into working on it as a separate package. Thanks.

**Comment by aalvrz** [comment]
Any updates on this?
