### ISSUE TITLE
use import statements instead of modifying globals() in webargs.fields

### ISSUE THREAD

**Issue by timfeirg** [marshmallow-code/webargs#116]
Inside [`webargs.fields`](https://github.com/sloria/webargs/blob/dev/webargs/fields.py#L28), `globals()` were modified in order to import all fields except `Nested` from marshmallow, I see two shortcomings in this:
- [`jedi`](https://github.com/davidhalter/jedi) won't be able to collect marshmallow fields from webargs
- hurts readability

can I send a PR to change this into `import` statements? It'd solve the above problems, but it'll require webargs to change its code when marshmallow adds fields

**Comment by marcellarius** [comment]
I'd definitely like to see this changed. It defeats Pycharm's code analysis/completion too and makes webargs.fields a pain to use vs. using marshmallow.fields directly.

**Comment by jasonab** [comment]
I've changed my imports to directly importing fields from marshmallow to avoid the PyCharm issues

**Comment by sloria** [comment]
Since marshmallow's `fields` module is relatively stable, I would be open to this change. It does add maintenance burden to keep webargs.fields up to date--perhaps we could add a test that ensures that `webargs.fields` contains all the Field classes in `marshmallow.fields`.

**Comment by lafrech** [comment]
Might be a noob question, but what is wrong with 

``` py
    from marshmallow.fields import *
```

since `Nested` is overridden anyway?

**Comment by sloria** [comment]
@lafrech That might work, but I'm not sure that solves the static analysis problem that this issue refers to.

**Comment by lafrech** [comment]
No, you're right, I just checked with Pylint and it apparently doesn't.

**Comment by sloria** [comment]
I'm going to close this for now. Implementing this adds more maintenance burden than I'm willing to take on right now. If you want to address the static analysis issue, I suggest importing from `marshmallow.fields` directly.
