### ISSUE TITLE
load_from is overriding field name, instead of acting as an alias

### ISSUE THREAD

**Issue by jasonab** [marshmallow-code/webargs#118]
In the Marshmallow docs, load_from is specifically named as an alias to the field name:

> Additional key to look for when deserializing. Will only be checked if the field’s name is not found on the input dictionary. If checked, it will return this parameter on error.

However, core.py line 276 uses the load_from name to override the arg name, if load_from is specified. This is not in line with marshmallow behavior.

**Comment by sloria** [comment]
@jasonab Just for my understanding: are you expecting that the field name is present in the request, that will be the key used in the errors output?

Example: Given an argdict `{'content_type': fields.Str(load_from='Content-Type', required=True)}`, webargs will first check if `content_type` is in the request before checking `Content-Type`. The errors output will be something like `{'content_type': ['Missing data for required field.']}`.

**Comment by jasonab** [comment]
Sorry, it's been a few months. :-)

I believe what I was expecting was that webargs would check both names in the request, first the actual key, and then the field name (as you mention in the example). Right now, I believe webargs will only check for the 'Content-Type' key, not 'content_type' in your example.

**Comment by sloria** [comment]
Makes sense. I think the behavior you're describing is the expected behavior, so this can be considered a bug. 

PRs welcome =)

**Comment by jasonab** [comment]
Thanks for fixing this. Sorry I didn't have a PR, I had some trouble running the tests on my side.

**Comment by sloria** [comment]
No worries!

**Comment by lafrech** [comment]
For the record, this changed in Marshmallow 3 (https://github.com/marshmallow-code/marshmallow/pull/714).
