### ISSUE TITLE
Handling redundant args in query string

### ISSUE THREAD

**Issue by JASON0916** [marshmallow-code/webargs#119]
I met a problem  when i use webargs to parse a api allow GET method. The query string contains something like `/api/xxx?id=&cno=&cs_name=jason&phone_date=&operator=&uodated_at=`
and i  use webargs in below way. The 400 was returned. Seems there is something wrong with the args.

``` python
param = args_parser.parse({
        'id': fields.Int(allow_missing=True),
        'cno': fields.Int(allow_missing=True),
        'cs_name': fields.Str(unicode, allow_missing=True),
        'phone_date': fields.Str(allow_missing=True),
        'operator': fields.Str(unicode, allow_missing=True),
        'updated_at': fields.Str(allow_missing=True)
    })
```

I read about the document and examples and can not find a way to filter the redundant args in query string, is there any solution?

**Comment by JASON0916** [comment]
I use flask code below to fix the problem temporarily, is there any better method?

```
from flask import request

param = {
        'id': request.args.get('id', None),
        'cno': request.args.get('cno', None),
        'cs_name': request.args.get('cs_name', ''),
        'phone_date': request.args.get('phone_date', ''),
        'operator': request.args.get('operator', ''),
        'updated_at': request.args.get('updated_at', '')
    }
```

**Comment by sloria** [comment]
I'm not sure I completely understand the problem. What error are you seeing? You may need to pass `allow_none=True` to your fields if you want to allow `None` as input.

**Comment by sloria** [comment]
Closing this for now. Feel free to comment and reopen if you need further clarification.
