### ISSUE TITLE
JSON payload unicode problem on flask

### ISSUE THREAD

**Issue by mickey06** [marshmallow-code/webargs#12]
Sending non ASCII text returns : 400 Bad Request

Browser side code :

```
$.ajax({
    url: "/comments/a123",
    type: "post",
    data: JSON.stringify({'cm': 'é'}),
    contentType: "application/json",
})
```

Server side code:

```
comment = {
    'cm': Arg(str),
}

@app.route('/comments/<string:comment_id>', methods=['POST'])
@webargs.flaskparser.use_args(comment)
def comments(args, comment_id):
    comment_markdown = args['cm']
```

**Comment by sloria** [comment]
Thanks for reporting. I will look into this this weekend.

**Comment by jmcarp** [comment]
If you're using Python 2.x, have you tried changing `Arg(str)` to `Arg(unicode)`?

**Comment by sloria** [comment]
As @jmcarp pointed out, using `Arg(unicode)` should do the trick. I've added a test in https://github.com/sloria/webargs/commit/bf081746cf04c44600d9eb68d39aa436b90b5763 to verify that this is the case.
