### ISSUE TITLE
Validating Variable URL Parameters

### ISSUE THREAD

**Issue by cmuell89** [marshmallow-code/webargs#125]
Hey @sloria ,

Really like webargs. Good stuff. 

I am building a backend JSON API using Flask-Restful. Flask's ability to parse out variable URL's is very convenient with GET requests. I would like to validate the input passed in as the 'classifier' variable paramter to my get(self, args, classifier) method (see below for an example). I've attempted to add a custom location onto the flask parser via the @parser.location_handler decorator. However, the variable part of the URL is not explicitly supplied to the Flasks Request object. I could use a regex parse what was passed into the URI from such fields as Request.base_url, Request.endpoint etc,. although it feels like a hack. I believe Flask passes this parameter to the Resource object so I am not sure if this is available to incorporate into webargs at the moment.

URI example:

```
https://localhost:3000/train_classifier/<string:classifier>

https://localhost:3000/train_classifier/classifier1
```

Code example:

```
class Train(Resource):

    decorators = [auth.login_required]
    validate_application_json = partial(valid_application_type, 'application/json')

    train_args = {
            'content_type': fields.Str(required=True, load_from='Content-Type', location='headers', validate=validate_application_json),
           # Something along these lines:
            'classifier': fields.Str(required=True, location='variableURL', validate=validate.OneOf(classifier1, classifier2)
        }

    @use_args(train_args)
    def get(self, args, classifier):
       ....
```

Some doc resources:
- http://flask.pocoo.org/docs/0.11/quickstart/#variable-rules
- http://flask.pocoo.org/docs/0.11/api/#incoming-request-data

If I am missing something obvious, feel free to slap me on the back of the head. Otherwise I think this would be a nice feature.

**Comment by sloria** [comment]
I think the `'view_args'` location should meet your use case.
