### ISSUE TITLE
Question: Moving from field dict to marshmallow schema requires using strict=True

### ISSUE THREAD

**Issue by avilaton** [marshmallow-code/webargs#127]
I introduced webargs into my project and started out building a parser using a dict of fields:

```
user_args = {
    'id': fields.Integer(),
    'active': fields.Bool(),
    'first_name': fields.Str(required=True, validate=validate.Length(min=2, max=38)),
}
```

which worked out great when using `@use_kwargs(user_args)`.
I then refactored this into a Marshmallow Schema

```
class UserSchema(Schema):
    id = fields.Integer()
    active = fields.Bool(required=True)
    first_name = fields.Str(required=True, validate=validate.Length(min=2, max=38))
```

and changed `@use_kwargs(UserSchema)` and it blew up. After a lot of reading, I learned that `strict=True` makes a schema raise exceptions on validation which I think is what we do on the dict case. The following

```
class UserSchema(Schema):

    class Meta(object):
        strict = True

    id = fields.Integer()
    active = fields.Bool(required=True)
    first_name = fields.Str(required=True,
                            validate=validate.Length(min=2, max=38))
```

works correctly.

As this was not obvious for me, I wanted to drop a note here and ask if you think we should add it to the docs of I should have done it differently.

Thanks for this awesome project by the way!

**Comment by lafrech** [comment]
There's a note about this in the docs:

http://webargs.readthedocs.io/en/latest/advanced.html#marshmallow-integration

> You should always set strict=True (either as a class Meta option or in the Schema’s constructor) when passing a schema to webargs. This will ensure that the parser’s error handler is invoked when expected.

**Comment by avilaton** [comment]
Closing with RTFM. Thanks @sloria.
