### ISSUE TITLE
`error` message for json payload not working

### ISSUE THREAD

**Issue by ispmarin** [marshmallow-code/webargs#14]
Hi all,

The `error` message on Arg() is not printing the error message if validation fails, but instead is printing only the default 400 message. 

```
from flask import Flask
from flask import request
from webargs import Arg
from webargs.flaskparser import FlaskParser

parser = FlaskParser()

app = Flask(__name__)

tracks_args = {
    'event': Arg(str, target='querystring'),
    'origin': Arg(str, validate=lambda w: w in ['suggest'], target='json', error='Invalid choice for     origin')
}

@app.route('/tracks/<string:event>', methods=['post'])
def post(event):
    args = parser.parse(tracks_args, request)
    print args
    print event

    return "OK"


if __name__ == '__main__':
    app.run(debug=True, port=8001)
```

with a correct request like

```
{
    "suggest":"test"
}
```

and an incorrect one like
     {
         "suggestsadf":"test"
     }
that should print the error message.
Thanks!

**Comment by sloria** [comment]
Webargs will use Flask's [`abort`](http://flask.pocoo.org/docs/0.10/api/#flask.abort) function to abort the current request. It will not handle returning a response automatically. 

You will need to add an error handler for your `Flask` app. See [here](http://flask.pocoo.org/docs/0.10/api/#flask.Flask.errorhandler) .

Webargs will attach additional data, including validation errors, to the HTTPException that your error handler receives. So if you wanted to return the validation message as JSON back to the client, you can do something like this:

``` python
from flask import Flask
from flask import request, jsonify
from webargs import Arg
from webargs.flaskparser import FlaskParser

parser = FlaskParser()

app = Flask(__name__)

tracks_args = {
    'event': Arg(str, target='querystring'),
    'origin': Arg(str, validate=lambda w: w in ['suggest'], target='json', error='Invalid choice for     origin')
}

@app.route('/tracks/<string:event>', methods=['post'])
def post(event):
    args = parser.parse(tracks_args, request)
    print(args)
    print(event)
    return "OK"


@app.errorhandler(400)
def handle_error(err):
    # webargs attaches additional metadata, including
    # validation errors, to the `data` attribute
    return jsonify({
        'message': str(err.data['message'])
    }), 400

if __name__ == '__main__':
    app.run(debug=True, port=8001)
```

**Comment by sloria** [comment]
I've added documentation for handling validation errors in Flask+webargs: http://webargs.readthedocs.org/en/dev/#error-handling. 

Hope this helps!

**Comment by ispmarin** [comment]
Thanks!
