### ISSUE TITLE
Docs: Validator function output behavior not clear for implicit None return.

### ISSUE THREAD

**Issue by tinproject** [marshmallow-code/webargs#143]
The [docs](https://github.com/sloria/webargs/blob/dev/docs/quickstart.rst#validation) about validation functions tells that:

> The validator may return either a boolean or raise a :exc:`ValidationError <webargs.core.ValidationError>`.

but the example below don't have a `return` statement, so an implicit `None` is returned. In this case is not clear in the documentation if the validator is seen as succeed or failed if a None is returned.

What is the expected behavior in this case?

**Comment by sloria** [comment]
Thanks for reporting. Validators that return `None` will _pass_ validation. I've added a note about this in the docs.
