### ISSUE TITLE
Feature request: parser for the Klein framework

### ISSUE THREAD

**Issue by pgpbpadilla** [marshmallow-code/webargs#151]
Add a parser for the [Klein](https://github.com/twisted/klein#example) framework.

**Comment by sloria** [comment]
I don't have plans to add this; this can be implemented as a separate library.

**Comment by rmax** [comment]
Hi @sloria, I just pushed a WIP PR that address this issue: https://github.com/sloria/webargs/pull/159

It's a twisted parser which is fully compatible with klein framework. Let me know if it's a good addition or better to release it as a `webargs-twisted` package.

**Comment by sloria** [comment]
@rolando Thanks for the contribution. I have decided not to add any new parsers for the time being. New parsers should exist as separate packages.

Let me know when you release `webargs-twisted`. I'll start a new section in the wiki with links to external packages.

**Comment by rmax** [comment]
@sloria sounds good to me!
