### ISSUE TITLE
supporting sanic

### ISSUE THREAD

**Issue by xidianwlc** [marshmallow-code/webargs#160]
is any roadmap to support sanic?

**Comment by sloria** [comment]
We have no plans to add a sanic parser to this repo. If you end up implementing it, feel free to post it here and I can link to it in the documentation.

**Comment by dnikolayev** [comment]
I found this page via Google. There was no support of Sanic. 

However, this pushed to create one, please check  [webargs-sanic](https://github.com/EndurantDevs/webargs-sanic)
