### ISSUE TITLE
webargs does not play well with Bottle plugins in Python 2.7

### ISSUE THREAD

**Issue by romabysen** [marshmallow-code/webargs#162]
When using use_args from the bottle parser on Python 2.7 any route using a Bottle plugin will fail with `TypeError: xxx() takes exactly X arguments (Y given)`. Code to replicate this issue is below. It uses the sqlite plugin but the same thing happens to other plugins, such as the sqlalchemy one. This happens only on 2.7, on 3.5 it works fine.

bottle==0.12.13
bottle-sqlite==0.1.3
webargs==1.6.0

```python
import bottle
from bottle.ext import sqlite
from webargs.bottleparser import use_args
from webargs import fields

ARGS = {
    'arg': fields.String(required=True),
}


app = bottle.default_app()
plugin = sqlite.Plugin(dbfile='/tmp/test.db')
app.install(plugin)


@app.route('/test')
@use_args(ARGS)
def test(args, db):
    return args


if __name__ == '__main__':
    bottle.run()
```

```shell
$ curl http://127.0.0.1:8080/test?arg=test`
```
```
Traceback (most recent call last):
  File "/home/lars/.pyenv/versions/webargs-fail/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/lars/.pyenv/versions/webargs-fail/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/lars/.pyenv/versions/webargs-fail/lib/python2.7/site-packages/webargs/core.py", line 445, in wrapper
    return func(*new_args, **kwargs)
TypeError: test() takes exactly 2 arguments (1 given)```

**Comment by sloria** [comment]
Thanks @romabysen for reporting. I would certainly review and merge a PR addressing this bug.

**Comment by romabysen** [comment]
I'll try to figure out why this happens but in the meantime there's a way to make it work; use the `apply` argument to `route`:

```python
@app.route('/test', apply=[use_args(ARGS)])
def test(args, db):
    return args
```

Using `apply` seems to be the "bottle way" so maybe it just works on 3.5 by accident.

**Comment by self-maurya** [comment]
@romabysen rather than passing plugin objects as positional arguments, you can pass then in **kwargs**. I am using sqlalchemy and flask-marshmallow in the same way.

```
kwargs = {'db': db_instance}

@app.route('/test')
def test(args, **kwargs):
    return args
```

**Comment by sloria** [comment]
As @romabysen pointed out, it seems like `apply` is the correct way to apply decorators to views in bottle. Perhaps we should just modify the documentation to use `apply`. How does that sound?
