### ISSUE TITLE
can arguments be made case-insensitive?

### ISSUE THREAD

**Issue by marcelhekking** [marshmallow-code/webargs#17]
Is it possible to make the arguments case-insensitive?

**Comment by sloria** [comment]
There is no built-in way to make an `Arg` case-insensitive. Many web frameworks implement a case-insensitive dict for the appropriate request argument source (e.g. headers).

One could implement case-insensitive headers by overriding how requests are parsed:

``` python
from webargs import core

class CaseInsensitiveParser(core.Parser):
    def parse_json(self, req, name, arg):
        json = req.json
        lower_keys = {k.lower(): k for k in json}
        if name.lower() in lower_keys:
            return json.get(lower_keys[name.lower()])
        else:
            return core.Missing

    # ...
```

**Comment by marcelhekking** [comment]
Thanx for the answer
