### ISSUE TITLE
Make wrapped functions returned by use_args introspectable

### ISSUE THREAD

**Issue by dwoz** [marshmallow-code/webargs#178]
It would be nice if there was a way to introspect the wrapped functions returned by Parser.use_args for the argmap associated with them. This would help for creating automated tools to generate things like documentation from webargs.

Assuming we did something like [this](https://github.com/sloria/webargs/compare/dev...dwoz:use_args-introspect), it would facilitate things like the following.

```python
app = Flask()

@app.route('/todo', method=['POST'])
@use_args({'item': fields.Str(required=True, description='The todo to add.')})
def add_todo(args):
       pass

swagger = {}

for rule in app.url_map.iter_rules():
    argmap = app.view_functions[rule.endpoint].__argmap__
    populate_swagger(swagger, rule, argmap)
```

Anyone else have thoughts on this?

**Comment by sloria** [comment]
The target use cases are addressed by writing higher-order decorators. [https://github.com/jmcarp/flask-apispec] takes this approach; it includes decorators that do both parsing and use [apispec](https://github.com/marshmallow-code/apispec) to generate Swagger documentation.

**Comment by dwoz** [comment]
Excellent, thanks!

**Comment by dwoz** [comment]
Figured I'd share my final solution in case it helps others.

```python
from webargs.flaskparser import FlaskParser

parser = FlaskParser()

def use_args(argmap, req=None, locations=None, as_kwargs=False, validate=None):
    if isinstance(argmap, collections.Mapping):
        argmap = argmap2schema(argmap)()
    func = parser.use_args(argmap, req, locations, as_kwargs, validate=None)
    func.__argmap__ = argmap
    return func
```
