### ISSUE TITLE
Embedded document (Dict) validation

### ISSUE THREAD

**Issue by dmitry-saritasa** [marshmallow-code/webargs#18]
hi Sloria,

Nice framework! Is it possible to validate embedded document (dict) within JSON?

``` python
dateadd_args = {
    'value': Arg(default=dt.datetime.utcnow, use=string_to_datetime),
    'data': {
             'param1': Arg(str, validate=validate_unit),
             'param2': Arg(str, validate=validate_unit),
             'parame3': Arg(str, validate=validate_unit)
    }
    'addend': Arg(int, required=True, validate=lambda val: val >= 0),
    'unit': Arg(str, validate=validate_unit)
}
```

is it possible?

thanks,
Dmitry

**Comment by sloria** [comment]
There is currently no built-in way to do validation of nested data. You would have to add a validator to the `data` arg.

``` python
def validate_unit_dict(val):
    for item in val.items():
        validate_unit(item)

'data': Arg(dict, validate=validate_unit_dict)
```

I have considered adding support for nested validation by allowing the `type_` argument to be a dictionary of `Arg` objects. The syntax would be very similar to what you have above.

``` python
'data': Arg({
    'param1': Arg(str, validate=validate_unit),
    #...
})
```

I need to think more about this feature, though.

**Comment by dgilland** [comment]
+1 for this. I currently use a class based object for the nested Arg type. Having builtin support for this would be great!

**Comment by sloria** [comment]
Added in 0.9.0
