### ISSUE TITLE
Getting exception when doing List(Nested(Schema))

### ISSUE THREAD

**Issue by beardedeagle** [marshmallow-code/webargs#182]
I have the following in my schema file:
```
import functools
from webargs.flaskparser import use_kwargs
from marshmallow import Schema
from marshmallow.fields import Str, List, Nested

HEADERS = functools.partial(use_kwargs, locations=('headers',))
PATH = functools.partial(use_kwargs, locations=('view_args',))
PAYLOAD = functools.partial(use_kwargs, locations=('json',))


class BaseSchema(Schema):

    class Meta(object):

        strict = True


class NestedData(BaseSchema):

    key = Str(required=True)
    value = Str(required=True)


class PatchPayload(BaseSchema):

    payload = List(Nested(NestedData, required=True), required=True)
```
And for a test view:
```
@API.route('/services/<string:service>/backendglobal', methods=['PATCH'])
@HEADERS(BaseHeader())
@PATH(BaseService())
@PAYLOAD(PatchPayload())
def patch_backendglobal(token, service, payload):
    print(token, service, payload)
    return('hi')
```
request:
```
curl -X PATCH "http://127.0.0.1:5000/api/v1/services/test-service1/backendglobal" -H "accept: application/json" -H "token: REDACTED" -H "content-type: application/json" -d "[ { \"key\": \"foo\", \"value\": \"bar\" }]"
```

However I am continually getting 422's with: `{'payload': ['Missing data for required field.']}`. If I just dump the incoming `request.json` I see the following: `[{'key': 'foo', 'value': 'bar'}]` which is what I am expecting. Am I missing something here?

**Comment by beardedeagle** [comment]
Only thing I can think of is you are expecting an object as root where I am providing an array.

**Comment by beardedeagle** [comment]
Additionally If I switch from `PatchPayload()` to `NestedData(many=True)` I get the following:
`AttributeError: 'list' object has no attribute 'keys'`

**Comment by beardedeagle** [comment]
Ok so I figured it out:
```
class PatchPayload(BaseSchema):

    payload = Nested(NestedData, required=True, many=True)

```
But this is not how webargs explains how it should be implemented. I had to dig into the marshmallow api docs to figure it out. Maybe something that can be doc'd on the webargs side?

**Comment by lafrech** [comment]
FWIW, there is an open issue about `List(Nested(...))` : https://github.com/marshmallow-code/marshmallow/issues/483.

**Comment by sloria** [comment]
As @beardedeagle pointed out, using `Nested(.., many=True)` is the correct approach. If this isn't clear in the docs, please send a PR =)
