### ISSUE TITLE
Error handling when using webargs together with Flask-RESTful

### ISSUE THREAD

**Issue by Ch00k** [marshmallow-code/webargs#19]
I'm having difficulties understanding how to deal with default webargs errors while using webargs together with flask-restful. I'm always getting this error when the arg validation fails:
`TypeError: ValidationError(u"Required parameter 'imdb_data' not found.", status_code=400) is not JSON serializable`
It's understandable that flask-restful expects a dictionary so it could serialize if to JSON. What I don't understand is how do I actually provide that dictionary.
I guess the solution proposed in #14 does not really fit here because it does not use flask-restful's error handling but flask's native. I would really appreciate an example of error handling for flask-restful.
This is how I use webargs:

``` python
imdb_data_json = {'imdb_data': Arg(dict, required=True)}

class MovieIMDBDataAPI(Resource):
    def __init__(self):
        super(MovieIMDBDataAPI, self).__init__()

    @use_args(imdb_data_json, targets=('json',))
        def put(self, args, movie_id):
            print args
```

If `imdb_data` validation fails I get the above exception.

**Comment by sloria** [comment]
Flask-RESTful will try to jsonify the `data` attribute of the raised `HTTPError` (see [here](https://github.com/flask-restful/flask-restful/blob/65c360d894cc68b65582fe9589dc09a6f2075a7c/flask_restful/__init__.py#L282)). In webargs, the data attribute contains the `ValidationError` object, which is not JSON-serializable. 

The solution here is to define an error handler for the webargs `FlaskParser` that will abort with JSON-serializable data.

Adding the following should fix your problem:

``` python
from flask.ext import restful
from webargs.flaskparser import parser

@parser.error_handler
def handle_request_parsing_error(err):
    code, msg = getattr(err, 'status_code', 400), getattr(err, 'message', 'Invalid Request')
    restful.abort(code, message=msg)
```

I will add a usage example with Flask-RESTful soon. Thanks for bringing this to my attention.

**Comment by sloria** [comment]
Added an example with Flask-RESTful [here](https://github.com/sloria/webargs/blob/dev/examples/flaskrestful_example.py).

**Comment by Ch00k** [comment]
Thanks!

**Comment by marbotte** [comment]
Something that might help other people, I found the most informative option to be:
```python
@parser.error_handler
def handle_request_parsing_error(err, req, schema, *, error_status_code, error_headers):
    """webargs error handler that uses Flask-RESTful's abort function to return
    a JSON error response to the client.
    """
    abort(422, errors=str(err))
```
