### ISSUE TITLE
Is there a support for the parser httptools?

### ISSUE THREAD

**Issue by garaud** [marshmallow-code/webargs#199]
Hi,

I use the [sanic](https://github.com/channelcat/sanic) framework, a Flask-like Python 3 framework with asyncio. This framework uses the [httptools](https://github.com/MagicStack/httptools) parser and I would like to known if there is an equivalent module in webargs for this parser.

If it's not the case, do you have some docs which explain how I can add a supported "framework" to webargs. I think this parser is quite similar to sanic, e.g. https://github.com/channelcat/sanic/blob/master/docs/sanic/request_data.md

Thanks,
Damien G.

**Comment by garaud** [comment]
I checked httptools. It's the http parser used for the Sanic web framework. A `sanicparser` should be great. I'll try to check the `core.Parser` to understand how doing that.

**Comment by sloria** [comment]
I'm not familiar with httptools.

I recommend taking a look at the existing `Parser` subclasses to see implementation examples. If you end up implementing webargs-sanic, let me know, and I can link to it in the docs.
