### ISSUE TITLE
Automatic documentation

### ISSUE THREAD

**Issue by AnakTeka** [marshmallow-code/webargs#206]
It stated in website that 

> Automatic documentation. The metadata that webargs provides can serve as an aid for automatically generating API documentation.

How do I use the automatic documentation? I'm using Falcon

**Comment by sloria** [comment]
webargs doesn't have API documentation generation out of the box, but it can be used together with apispec to generate an OpenAPI spec. 

See [flask-apispec](https://github.com/jmcarp/flask-apispec) for an example project that weaves webargs and apispec together.

**Comment by lafrech** [comment]
FWIW, here's another example: https://github.com/Nobatek/flask-rest-api of marshmallow/webargs/apispec gluing.
