### ISSUE TITLE
allow_none doesn't work,  need a default none argment.

### ISSUE THREAD

**Issue by eromoe** [marshmallow-code/webargs#218]
For example: 

code:
```
@use_args({'corpus_id': fields.Str(allow_none =True) })
def test(args):
    print('corpus_id', args['corpus_id'])
```

`GET  localhost:5000/test` would result  `KeyError: 'corpus_id'` .

I want 

1.  `GET  localhost:5000/test`   get  `args['corpus_id']==None`
1.  `GET  localhost:5000/test?corpus_id=1`   get  `args['corpus_id']==1`

I tried `fields.Str(default=None)` and `fields.Str(allow_none=True)` , both not work

**Comment by lafrech** [comment]
What you want is `missing=None`.

http://marshmallow.readthedocs.io/en/latest/api_reference.html#module-marshmallow.fields

`missing` provides default value for deserialization
`default` provides default value for serialization
`allow_none` allows to pass `None` (or `null` in JSON)

If `missing=None` and `allow_none` is unset, `allow_none` will default to True.
