### ISSUE TITLE
How to receive id  from the url,  and the other data from json

### ISSUE THREAD

**Issue by reem-codes** [marshmallow-code/webargs#227]
Hello

I have a UserView class like this:
```python
class UserView(FlaskView):
    trailing_slash = False
    model = User
    schema = user_schema

    @use_kwargs(schema.fields)
    def post(self, **kwargs):
        try:
            entity = self.model()

            for d in kwargs:
                if kwargs[d] is not missing:
                    entity.__setattr__(d, kwargs[d])

            db.session.add(entity)
            db.session.commit()
            o = self.schema.dump(entity).data
            return jsonify({'{}'.format(self.model.__table__.name): o})

        except IntegrityError:
            return jsonify({'message': '{} exist in the database. choose another id'
                   .format(self.model.__table__.name)}), 409


    @use_kwargs(schema.fields)
    def put(self, id, **kwargs):
        entity = self.model.query.filter_by(id=id).first_or_404()

        for d in kwargs:
            if kwargs[d] is not missing:
                entity.__setattr__(d, kwargs[d])

        db.session.commit()
        o = self.schema.dump(entity).data
        return jsonify({'{}'.format(self.model.__table__.name): o})

UserView.register(app)
```

how to make it so the id is taken from the url, and all other fields to be updated from json? my implementation right now force me to specify the id in my json. and even if the id specified was different that the url the one taken in calculation is the one in json body

**Comment by lafrech** [comment]
I think the sample code misses `app.route` statements.

**Comment by reem-codes** [comment]
@lafrech  nope, I am using classful which handle all the routing automatically

**Comment by lafrech** [comment]
OK, I don't know `classful`. I had a quick glance but didn't see that.

AFAIU, if you're using `use_kwargs` from `flaskparser.py`, it should work. Maybe the example in the docs could be improved about this, showing a path parameter being passed.

In the view function, do you get the id in `flask.request.view_args()`?

**Comment by reem-codes** [comment]
@lafrech THANK YOU! I made some changes and instead of ....
```
entity = self.model.query.filter_by(id=id).first_or_404()
```

 I made it
```
entity = self.model.query.filter_by(id=request.view_args['id']).first_or_404()
```

and it worked like I charm :D

**Comment by lafrech** [comment]
Alright. But this (`request.view_args['id']`) is precisely what webargs is supposed to do (https://github.com/sloria/webargs/blob/dev/webargs/flaskparser.py#L54).

Are you sure you're using `use_kwargs` from `flaskparser.py` and not from `core.py`?

**Comment by reem-codes** [comment]
@lafrech I believe so. this is my import statement

`from webargs.flaskparser import use_kwargs`

**Comment by lafrech** [comment]
Sorry, I think I was kinda wrong. Flask should inject the path parameter in the function, whether or not webargs is used.

The docs do provide [an example](https://webargs.readthedocs.io/en/latest/framework_support.html#decorator-usage) of getting a path parameter not parsed by webargs:

```python
from webargs import fields
from webargs.flaskparser import use_args

@app.route('/user/<int:uid>')
@use_args({'per_page': fields.Int()})
def user_detail(args, uid):
    return ('The user page for user {uid}, '
            'showing {per_page} posts.').format(uid=uid,
                                                per_page=args['per_page'])
```

Webargs optionnaly [parses path parameters](https://webargs.readthedocs.io/en/latest/framework_support.html#url-matches):

```python
from webargs.flaskparser import use_args

@app.route('/greeting/<name>/')
@use_args({'name': fields.Str(location='view_args')})
def greeting(args, **kwargs):
    return 'Hello {}'.format(args['name'])
```

In this case, the value parsed by webargs overrides the value injected by flask, IIUC.

> my implementation right now force me to specify the id in my json

You mean if you don't specify it in the json, it is not injected in the view function?

Does it make any difference if you make `id` `dump_only` in `user_schema`? It shouldn't, but I don't see anything useful you could try.

**Comment by sloria** [comment]
@reem-codes Are you still experiencing this issue, or can this be closed?
