### ISSUE TITLE
Docs: Add example for parsing files

### ISSUE THREAD

**Issue by Kamforka** [marshmallow-code/webargs#230]
Hey guys,

I've been consulting the documentation and the web for a proper solution to parse file arguments from a post request using `webargs`, but still couldn't find an answer to my question.

The [docs says](http://webargs.readthedocs.io/en/latest/quickstart.html#request-locations) you can use the `files` location during parsing but mentions no straightforward solution on which field to use for files? 

Can you include an example in the docs for this one, if it's possible to do at all?

**Comment by sloria** [comment]
If you use `fields.Field`, marshmallow won't do any processing on the value, so you'll get a framework-specific file wrapper object. For example, you'll get a [FileStorage](http://werkzeug.pocoo.org/docs/0.14/datastructures/#werkzeug.datastructures.FileStorage) object in Flask.

**Comment by Kamforka** [comment]
@sloria tried it, works, really nice.
Such a shame though that I couldn't find any docs about it elsewhere. 

However, really like what you are doing so keep up the good work!

**Comment by sloria** [comment]
@Kamforka Glad that worked. Good point about the docs. I'd certainly review/merge a PR adding an example in the docs =) .

**Comment by mholtzman** [comment]
@sloria I got a working example in Flask but I don't see an obvious place for it in the docs, it seems to be just basic usage or Marshmallow-specific on how to use the fields.Field() method. Any suggestions on where this might go?

Here's what it might look like, showing how to validate a file:
```
@app.route('/', methods=['POST'])
@use_kwargs({'json_data': fields.Field(validate=lambda file: file.mimetype == 'application/json', location="files")})
def upload_json(json_data):
    save_file(file_to_upload)
    return 'Succesfully uploaded JSON file'
```

**Comment by sloria** [comment]
Thanks @mholtzman . I went ahead and added it to the "Quickstart" page.

**Comment by mivade** [comment]
Hmm, looks like this example isn't there anymore. Has it moved elsewhere?

**Comment by kexinshine** [comment]
Hhhh，i‘ve been looking for a long time,tooooo...

**Comment by MMohan1** [comment]
+1

**Comment by johnlinp** [comment]
+1

**Comment by johnny-cy** [comment]
It seems not working for me, postman upload through body->form-data->choose a zip file and put 'file' in its key, it still gave me 422 when I set required=True, don't know why, here is what I tried 
`
@use_kwargs({"file": fields.Field(validate=lambda file: "zip" == file.filename.split(".")[-1].lower(), location="files", required=True)})
`
and couldn't find fields.Field validate on doc or anywhere, am I doing it correct ?

**Comment by mivade** [comment]
I was able to put together a small demo on how to use this properly with Tornado: https://gist.github.com/mivade/c0c31a966a13d7324d61d003ebd1b5ac. Working with files remains poorly documented though.

**Comment by johnny-cy** [comment]
> It seems not working for me, postman upload through body->form-data->choose a zip file and put 'file' in its key, it still gave me 422 when I set required=True, don't know why, here is what I tried
> `@use_kwargs({"file": fields.Field(validate=lambda file: "zip" == file.filename.split(".")[-1].lower(), location="files", required=True)})`
> and couldn't find fields.Field validate on doc or anywhere, am I doing it correct ?

I found the problem I put location in wrong place, it should be put as second arg of use_kwargs:
`@use_kwargs({"file": fields.Field(validate=lambda file: "zip" == file.filename.split(".")[-1].lower(), required=True)}, location="files")`
