### ISSUE TITLE
Flask-webargs both url path parameter and query parameter

### ISSUE THREAD

**Issue by uMtMu** [marshmallow-code/webargs#233]
Hi, i have a problem about accessing request parameter. I'm using
	  flask and webargs. I can get
	  http://localhost:5000/task/12?name=mysql id=12 and name=mysql with
	  app.route but i couldn't do it with app.add_url_rule.
	  https://gist.github.com/uMtMu/be0682823140e2b1418d6795203477e0

**Comment by sloria** [comment]
The view args will still get passed to your method view. You can add `**kwargs`` so that the `id` argument will be handled.

```python
class Task(MethodView):

    @use_args({'id': fields.Str(location='view_args'), 'name': fields.Str()})
    def get(self, args, **kwargs):
        return 'Hello {} {}'.format(args['id'], args['name'])

```
