### ISSUE TITLE
Feature: Accept the jQuery default serialization scheme for arrays

### ISSUE THREAD

**Issue by remeika** [marshmallow-code/webargs#235]
When serializing an array in to a query string, jQuery has the following behavior:

```
alert($.param( {b: [ 1, 2, 3 ]} ));
// alerts "b[]=1&b[]=2&b[]=3"
```

[As of jQuery 1.4, this behavior is the default](https://api.jquery.com/jquery.param/).

Webargs should support deserializing fields of type List from this format.

**Comment by remeika** [comment]
NB: I plan on building this in the next few months.

**Comment by lafrech** [comment]
Could this be a [custom parser](https://webargs.readthedocs.io/en/latest/advanced.html#custom-parsers)'s job?

**Comment by remeika** [comment]
Absolutely. I guess my presumption here is that jQuery is such a widespread frontend library that the ability to handle its default behavior should be built in, or maybe even the default.

Action on me to do a survey of some other frontend request libraries to see if they have similar default behavior.

**Comment by sloria** [comment]
Closing, as we won't be able to get to this in the near future. Feel free to comment if there's still interest in this.
