### ISSUE TITLE
How can documentation generators introspect a webargs field?

### ISSUE THREAD

**Issue by remeika** [marshmallow-code/webargs#236]
The introductory documentation to webargs lists one framework feature as:

> Automatic documentation. The metadata that webargs provides can serve as an aid for automatically generating API documentation.

Any pointers on where to access that metadata?

**Comment by lafrech** [comment]
I have no idea what metadata the doc is talking about.

If you're interested in automatic doc generation, you should pay a look at [apispec](https://github.com/marshmallow-code/apispec).

Adding a layer on top of marshmallow/apispec/webargs allows you to specify schemas for input/output and document them at the same time. This is what [flask-apispec](https://github.com/jmcarp/flask-apispec) or [flask-rest-api](https://github.com/Nobatek/flask-rest-api) do.

**Comment by sloria** [comment]
That bit is referring to the metadata stored on fields, in the form of stored arguments. For example:

```python

>>> f = fields.Str(required=True, description='Your username')
>>> f.required
True
>>> f.metadata
{'description': 'Your username'}
```

Because input schemas are separated from view functions, libraries (like the ones @lafrech mentioned) can easily introspect the schemas and generate API specifications.

**Comment by lafrech** [comment]
> That bit is referring to the metadata stored on fields

Oh, of course. I didn't think of that.
