### ISSUE TITLE
Advice wanted: returning args in response.

### ISSUE THREAD

**Issue by rclough** [marshmallow-code/webargs#251]
Hello,

I'm using webargs for a simple GET/POST endpoint in flask. I'm using webargs as a decorator to validate the input which can accept arguments both from URL params and JSON post.

As part of my API responses, I want to be able to return all of the request params on either a succesful or failed request, which can help with debugging, context management, etc. To do this, I'm using `parser.parse()` which sources the arguments from the various locations, which is why I'm using webargs in the first place.

```Python
@app.route('/info/<int:obj_id>', methods = ['GET'])
@app.route('/info', methods = ['GET', 'POST'])
@use_args(nn_args, as_kwargs=True, locations=('query', 'json', 'view_args'))
def info(obj_id, num_results, search_factor, context):
    result = manager.get_info(obj_id, num_results, search_factor)
    
    results = api_response().dump({
        "results": result.data,
        "success": True,
        "ts": dt.now(),
        "request": parser.parse(nn_args, locations=('query', 'json', 'view_args'))
    })
    return jsonify(results.data)
```

Unfortunately, this becomes an issue when I need to form an error response for a `ValidationError` where one of the request params doesnt validate. I'm handling 422 error codes like so:

```Python
@app.errorhandler(422)
def handle_unprocessable_entity(err):
    exc = getattr(err, 'exc')
    if exc:
        messages = exc.messages
    else:
        messages = ['Invalid request']
    return jsonify({
        'error': messages,
        "success": False,
        "ts": dt.now(),
        'request:': parser.parse(nn_args, locations=('query', 'json', 'view_args'))
    }), 422
```

However, when I call `parser.parse()` this time, it will just throw the 422 error again and again due to the validation errors.

At this point I'm pretty sure I'm not using the library correclty for what I want, so my questions:

1. Is there a way to disable validation for the purposes of returning the actual arguments made in the request when an error happens?
2. Should I be using a different function to get all of the arguments, potentially one without declaring a schema/validation (which would solve my need to explicitly declare a "context" object in the schema)

**Comment by lafrech** [comment]
You could get the raw arguments straight from the `flask.request` object.

**Comment by rclough** [comment]
Fair enough, I'll just write a function to pull out the relevant parameters from each, it just seems that I'm effectively replicating what I wanted web args to do in the first place, which was handle all the different argument locations and coalesce them into a singular structure. Though I suspect you cant really suppress errors during the parse cause there's probably cases where the correct output is undefined for some errors.

Anyways, thanks

**Comment by lafrech** [comment]
> Though I suspect you cant really suppress errors during the parse cause there's probably cases where the correct output is undefined for some errors.

Yes, I think that makes things complicated. You may spend more time grabbing from webargs what you don't want to replicate than coding it specifically for you own use case.
