### ISSUE TITLE
FalconParser should ideally support falcon's native media decoding

### ISSUE THREAD

**Issue by foresmac** [marshmallow-code/webargs#253]
Falcon has a native media handling mechanism which can decode an incoming request body based on the `Content-Type` header and adding the dictionary of resulting key-value pairs as a cached property `req.media`. I've written my own FalconParser subclass that (very naively) uses this, but it seems like something that might be worth supporting out of the box.

```python
    def parse_json(self, req, name, field):
        """
        Pull a JSON body value from the request.
        uses falcon's native req.media
        """
        json_data = self._cache.get("json_data")
        if json_data is None:
            self._cache["json_data"] = json_data = req.media
        return core.get_value(json_data, name, field, allow_many_nested=True)
```

This could probably be improved upon; since the `media` property  is already cached on the request object, we could just access `req.media` directly without caching on the parser. (Not sure if this impacts other things that might use that cache, though; I haven't dug deep enough to fully understand that implication.) Also, since `media` was added in 1.3, if webargs still wanted to support older versions of falcon we could add a check for it and fall back to the existing behavior.

Maybe something like:

```python
    def parse_json(self, req, name, field):
        """Pull a JSON body value from the request.
        .. note::
            The request stream will be read and left at EOF.
        """
        json_data = req.media if hasattr(req, 'media') else self._cache.get("json_data")
        if json_data is None:
            self._cache["json_data"] = json_data = parse_json_body(req)
        return core.get_value(json_data, name, field, allow_many_nested=True)
```

**Comment by sloria** [comment]
I'm open to this, though it might make Falcon's parsing inconsistent with the other parsers. But perhaps that's OK, since Falcon users may expect `req.media` to be used.

I'd certainly review/merge a PR.

**Comment by sirosen** [comment]
I'm looking at this as something we can clean out of the backlog.
After 6.0, we now are supporting falcon 2.x only, so I think it's quite easy.

I'd rather define `media` as a distinct location. So you could use a falcon parser with `location="media"` and it will do basically what was proposed above (modified suitably to fit with webargs v6).

We could even add a note for webargs 7.0 to upgrade to have `FalconParser.DEFAULT_LOCATION = "media"`, which would tweak the default. Everything remains consistent that way, and we don't muddle `json` with the `media` behavior. I don't know that I'd like to make that change in 6.x -- it feels too breaky for too specific of a niche for me.

If someone submitted a PR with that, I'd happily review, but I'll try to remember to get to it at some point soon.

**Comment by sirosen** [comment]
@lafrech, I haven't looked at this in a while, but I think maybe we should do it as part of 7.0. I'm adding it to the milestone and we can take it out if desired.

Falcon is the framework I'm probably least familiar with, so I'll want to read up on this feature again to make sure I understand what `req.media` does/is.

**Comment by foresmac** [comment]
Thank you @sirosen 👍🏼
