### ISSUE TITLE
4.0.0 not returning JSON error

### ISSUE THREAD

**Issue by csheppard** [marshmallow-code/webargs#255]
Hey, I'm using marshmallow 3.0.0b12 and Flask-RESTful.

After upgrading to webargs 4.0.0, Flask will error with a 422 but produce the default HTML error message:

**webargs 4.0.0**
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>422 Unprocessable Entity</title>
<h1>Unprocessable Entity</h1>
<p>The request was well-formed but was unable to be followed due to semantic errors.</p>
```

**webargs 3.0.2**
```json
{
    "messages": {
        "email": [
            "Not a valid email address."
        ]
    }
}
```

```python
from marshmallow import Schema, fields

class SomeSchema(Schema):
    email = fields.Email(
        missing=None,
        load_only=True
    )

@use_args(UserSchema())
def some_route(args):
    pass
```

**Comment by csheppard** [comment]
Looking at the latest changes, I guess Flask-RESTful error handling may need tweaking?

**Comment by jasonehines** [comment]
I'm getting this with Flask-Marshmallow.

**Comment by sloria** [comment]
You need to use a Flask error handler to return a JSON response for 422 errors: https://webargs.readthedocs.io/en/latest/framework_support.html#error-handling .
