### ISSUE TITLE
Docs: Add example for using NestedQueryFlaskParser

### ISSUE THREAD

**Issue by aknvictor** [marshmallow-code/webargs#263]
The docs provide a custom parser class for Nested Queries: http://webargs.readthedocs.io/en/latest/advanced.html#custom-parsers

It would be great to have an example of how to use this. Can one use 'use_kwargs' and can one have arguments that are not nested?

**Comment by sirosen** [comment]
I keep coming back to this issue and trying to choose whether to close it or to add some doc to explain more.

> Can one use 'use_kwargs' and can one have arguments that are not nested?

Yes, and yes.

The docs give a pretty good (IMO) statement of what the example does:
```
    For example, the URL query params `?name.first=John&name.last=Boone`
    will yield the following dict:

        {
            'name': {
                'first': 'John',
                'last': 'Boone',
            }
        }
```

The feature being documented is the ability to customize parsers to do whatever one might wish, not specifically the example code. I think that for anyone interested in copy-pasting the example (no shame in that!), they'd be best served by playing with it in a python repl and seeing what it does.

I'm going to close this. If this is really unclear or there's some angle I'm not seeing on this, please feel free to reopen!

**Comment by sarimmehdi** [comment]
There is no example that shows how to use a custom_parser with use_kwargs. Please add that to the documentation
