### ISSUE TITLE
Inconsistent behavior in passing request fields to Schema.load (many=True vs many=False)

### ISSUE THREAD

**Issue by tuukkamustonen** [marshmallow-code/webargs#268]
With `4.0.0` (and marshmallow `3.0.0b13`):

```python
class Sch(Schema):
    foo = fields.Str()

parser = FlaskParser()

req = Mock()
req.mimetype = 'application/json'

req.get_json = lambda *args, **kwargs: [{'extra': 1}]
with pytest.raises(UnprocessableEntity) as e:
    parser.parse(Foo(many=True), req=req, locations=('json', ))
assert e.value.exc.messages == {0: {'extra': ['Unknown field.']}}

req.get_json = lambda *args, **kwargs: {'extra': 1}
parser.parse(Foo(), req=req, locations=('json', ))
```

So the with `many=True` the extra key is actually passed to `Schema.load()` (which can then raise `ValidationError` because `unknown` defaults to `RAISE`) but with `many=False` it is passed onwards. I think it's confusing.

#267 would fix this.

**Comment by lafrech** [comment]
@tuukkamustonen is this fixed in webargs 6 beta?

**Comment by tuukkamustonen** [comment]
@lafrech I haven't been able to follow the project lately, but as the referenced ticket #267 has been fixed and merged, I would assume so.

Feel free to close, if you think this is fixed, we can re-open if it's not...

**Comment by lafrech** [comment]
Fixed.

```py
from werkzeug.exceptions import UnprocessableEntity
from marshmallow import Schema, fields
from webargs.flaskparser import FlaskParser
from unittest.mock import Mock


class Foo(Schema):
    foo = fields.Str()

parser = FlaskParser()

req = Mock()
req.mimetype = 'application/json'

req.get_data = lambda *args, **kwargs: '[{"extra": 1}]'

# Both raise UnprocessableEntity
try:
    parser.parse(Foo(many=True), req=req, location='json')
except UnprocessableEntity:
    print('OK')
try:
    parser.parse(Foo(), req=req, location='json')
except UnprocessableEntity:
    print('OK')
```

**Comment by tuukkamustonen** [comment]
This indeed looks like fixed now. Thanks for checking!

**Comment by tuukkamustonen** [comment]
Just a minor "correction":

The latter case, with `many=False` actually failed with just `{"extra": 1}` not `[{"extra": 1}]` (as in your code above).

But both those now raise error properly, so yeah it's fixed.
