### ISSUE TITLE
Compatibility of `multiple=True` with nested args

### ISSUE THREAD

**Issue by dgilland** [marshmallow-code/webargs#29]
Correct me if I'm wrong, but it doesn't seem like nested args supports lists of dicts.

For example, using this:

``` python
args = {
    'collection': Arg({'foo': Arg(), 'bar': Arg()}, multiple=True)
}
```

to parse incoming data like this:

``` python
incoming = [
    {'foo': 1, 'bar': 2},
    {'foo': 3, 'bar': 4},
    {'foo': 5, 'bar': 6}
]
```

**Comment by sloria** [comment]
`multiple=True` should work as expected with nested `Args`.

I've written a test case to verify this here: https://github.com/sloria/webargs/blob/09eceaf120ed4cba88c2c959661c3d52b883d495/tests/test_core.py#L242-254

**Comment by dgilland** [comment]
My usage was with how the various parsers process the args.

For example, if you look at [flaskparser.parse_json](https://github.com/sloria/webargs/blob/d8692b397e9c199500df7354c7bccd425ee2c727/webargs/flaskparser.py#L53), it passes `arg.multiple` to `core.get_value`. Then in [core.get_value](https://github.com/sloria/webargs/blob/d8692b397e9c199500df7354c7bccd425ee2c727/webargs/core.py#L91), this [line](https://github.com/sloria/webargs/blob/d8692b397e9c199500df7354c7bccd425ee2c727/webargs/core.py#L106) gets hit which wraps the JSON data value in a list.

So instead of receiving `[{...}, {...}]`, the value is passed as `[[{...}, {...}]]` which then fails validation check.

**Comment by sloria** [comment]
Hotfix is in the latest release on the PyPI. Thanks for reporting this!

**Comment by gowhari** [comment]
For newer versions `many` works:

``` python
@use_args({
    'col': fields.Nested({
        'foo': fields.Str(),
        'bar': fields.Str(),
    }, many=True)
})
```

``` bash
curl -d '{"col": [{"foo": "1"}, {"bar": "2"}]}'  -X POST -H 'content-type: application/json' http://server/route 
```
