### ISSUE TITLE
Confused - how to use List/Nested

### ISSUE THREAD

**Issue by nazariyv** [marshmallow-code/webargs#303]
Can you help me understand how to use the structure like below to achieve something like this: 

```py
 {"config":{"factor_1":[{"comparator":"<=", "value":"20"},{"comparator":">=", "value":"10"}],
               "factor_2":[{"comparator":"<=", "value": "PE"}],
               "factor_3":[{"comparator":"exactly", "value": "AAA+"}]}
```

```py
class ComparatorValue(Schema):
    comparator = fields.Str(required=True)
    value = fields.Str(required=True)

    @validates('comparator')
    def validate_comprator(self, comparator):
        if comparator not in comparators:
            raise ValidationError("Invalid comparator: {}. Allowed values: {}".format(comparator, comparators))

    class Meta:
        strict = True


class ConfigSchema(Schema):
    """
    {"config":{"factor_1":[{"comparator":"<=", "value":"20"},{"comparator":">=", "value":"10"}],
               "factor_2":[{"comparator":"<=", "value": "PE"}],
               "factor_3":[{"comparator":"exactly", "value": "AAA+"}]}
    """
    config = fields.Dict(keys=fields.Str(required=True),
                         values=fields.Nested(ComparatorValue), required=True)
    # comparator = fields.Str()
    # # value = fields.Str(required=True)
    #


    @validates('config')
    def validate_config(self, config):
        keys = list(config.keys())
        vals = list(config.values())
        for key in keys:
            if key != '':
                raise ValidationError("Factor name cannot be empty.")
        # for val in vals:
        #     if

    class Meta:
        strict = True

def get_api():

    class BondScreenApi(Resource):
        @use_args(ConfigSchema())
        def post(self, args):
            # comparator = args['comparator']
            # value = args['value']
            print(args['config'])
            print("Posted args: {}".format(args))
            return {"Got": "Through"}, 201

    return BondScreenApi
```

As soon as I add Nested/List, it stops working, as in it successfully goes through all of the validation, even though the args are not correct. For example, if for values we have `fields.List(Nested(ComparatorValue))` (this is actually what I need, I've given above a minimal example), then any request where the data is like: `{"config": {"yo":"got through"}}` goes through, even though the value of "yo" is supposed to be a `List(Nested(...))`. I am clearly misunderstanding how to use it and I cannot find a lot of examples on the Internet.

**Comment by lafrech** [comment]
Did you mean to post on marshmallow bugtracker? This is webargs.

Edit: OK, I just saw the webargs usage at the bottom of your code. Still, it looks like a marshmallow question. No big deal. But more audience on marshmallow bugtracker.

**Comment by nazariyv** [comment]
This is marshmallow integration with webargs: `use_args(ConfigSchema())`

**Comment by lafrech** [comment]
You can get webargs out of the way by loading your data with the Schema directly.

    ConfigSchema().load({"config": {"yo":"got through"}})

Looks like you're using a mix of marshmallow 2 and 3. Meta.strict is marshmallow 2, Dict with keys/values validation is marshmallow 3 (still beta).

**Comment by nazariyv** [comment]
Thanks. When I check my version of marshmallow it is `2.15.6`. How can I be using the feature of `Dict` in this version, if it is in version `3`? How would I fix this code to achieve the desired result?

**Comment by lafrech** [comment]
Dict exists in marshmallow 2 but it ignores keys/values arguments so it does not perform the validation you expect, hence the result.

**Comment by nazariyv** [comment]
Thanks. Is it a bad idea to upgrade to marshmallow 3?

**Comment by lafrech** [comment]
Depends on your project. Looks like you're starting something so go for it. Just beware of the updates, pin your versions, read the changelog. We hope to release a 3.0 soonish.

**Comment by nazariyv** [comment]
Thanks for your help!
