### ISSUE TITLE
Validating files in Flask is broken

### ISSUE THREAD

**Issue by yani-** [marshmallow-code/webargs#31]
Example code:

``` python
@app.route('/', methods=['post'])
@use_args({'file': Arg(FileStorage, required=True, target='files')})
def index(args):
    print(args.get('file'))          # <FileStorage: 'file' (None)>
    print(request.files.get('file')) # <FileStorage: 'readme.md' ('application/octet-stream')>

    return '', 200
```

Python 3.4
webargs==0.10.0

The problem is in `core.py` line 216 where we do conversion to type:
`ret = self.type(ret)`
One way to fix this is by making the conversion optional?

**Comment by sloria** [comment]
@yani- Apologies for the delayed response. 

The `type_` conversion argument is optional, so your example should work if you remove `FileStorage` from the `Arg`.

**Comment by yani-** [comment]
Thank you @sloria 
In that case, I will probably need to use lambda to validate that the file is of type FileStorage?

**Comment by sloria** [comment]
@yani- Correct, the `type_` parameter is for conversion; use `validate` for validation.

**Comment by yani-** [comment]
Thank you @sloria
