### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizergit** [marshmallow-code/webargs#312]
Greetings, @sloria 

My apologies in case this is not the right channel to address this. I'm a designer in development and an open source enthusiast, who exploring GitHub found your project and decided to propose a logo design for it. It's (of course) totally free and we would be working together to create the design that fits best. In case you agree, you could share some ideas you may have (colours, shapes, etc) so I have something to start with. 

Kind regards and keep up the great work!

**Comment by sloria** [comment]
Wow, that is very generous of you, @michaelizergit ! A logo would be great.

Where do we start? First, a bit about webargs: it's a library for parsing and validating input from HTTP requests. It works with many of Python's popular web frameworks.

How about you post some ideas you have, and we can iterate from there?

**Comment by michaelizergit** [comment]
Hello, I'm so sorry for disappearing I was finishing a semester. I want to resume the work as soon as possible just passing by to ask if you are still interested.

**Comment by sloria** [comment]
No problem @michaelizergit . I'm still interested as long as you're still willing to do it. No rush, of course.

**Comment by michaelizergit** [comment]
Hello again, here are some ideas. What do you think?
![logos](https://user-images.githubusercontent.com/43072298/50058974-f9b95a00-0156-11e9-8078-c5f39bd069d5.jpg)

**Comment by sloria** [comment]
Nice, @michaelizergit ! Can you lowercase the "w" to be consistent with the casing in the docs?

**Comment by michaelizergit** [comment]
Sure! I need you to tell me which one you prefer most, or if you didn't like any so we can start making modifications from there. Also name anything else you'd like to modify: shapes, colors, etc.

**Comment by sloria** [comment]
I like the multi-colored parallelogram ones the most. Let's start there. Are there other color palettes you considered?

**Comment by michaelizergit** [comment]
Very good, I was thinking on trying with python colors, but please, share the codes of the colors you may have in mind and I'll try with those too.

**Comment by sloria** [comment]
I didn't have any specific colors in mind. Just thought it'd be nice to see alternatives. Nice work so far!

**Comment by michaelizergit** [comment]
Very well, working on it :muscle:

**Comment by michaelizergit** [comment]
Hello there, here you have some sketches, want to hear your opinion.
![logos](https://user-images.githubusercontent.com/43072298/50497868-19cc0180-0a12-11e9-846b-45a1e4b6d285.png)

**Comment by sloria** [comment]
Thanks @michaelizergit ! 

Let's go with the lowercased "webargs". As for the colors, here are my favorites:

![image 2018-12-28 08-36-22](https://user-images.githubusercontent.com/2379650/50516978-e0c87700-0a7b-11e9-9418-c4f6ff08b2e3.png)

**Comment by michaelizergit** [comment]
I personally like this one 
![screenshot_2018-12-30 50497868-19cc0180-0a12-11e9-846b-45a1e4b6d285 png png image 2554 x 3304 pixels](https://user-images.githubusercontent.com/43072298/50552224-0cf31c00-0c65-11e9-8a23-87f545f34709.png)

And this one (all lowercase)
![screenshot_2018-12-30 50497868-19cc0180-0a12-11e9-846b-45a1e4b6d285 png png image 2554 x 3304 pixels 1](https://user-images.githubusercontent.com/43072298/50552231-1bd9ce80-0c65-11e9-9b9d-449bbc573a33.png)

Which one you liked most?

**Comment by sloria** [comment]
Of those two, I like the top one more.

Can you also try some solid-colored ones for comparison?

Here are some colors I think might work:

#fa153a
#fb0091
#25ba81

**Comment by michaelizergit** [comment]
Working on it

**Comment by michaelizergit** [comment]
Finally, here are the samples for comparison. Want to hear your opinion

![Sin título-1-01](https://user-images.githubusercontent.com/43072298/56390439-067bb680-61fa-11e9-8c2f-0a430975fa8b.jpg)

**Comment by sloria** [comment]
Thanks. The green is too bright, so let's scratch that one. How about #25ba81?

**Comment by sirosen** [comment]
This thread has been quiet for a while, but I'd happily work on integrating some version of this logo into the docs site and readme when I have time.

The only remaining concerns, I think, are:

- Is there a final image (or set of images) to use for this?

@sloria proposed a color which seems good to me, but I'd also be happy with something dark like the bottom of the three solid-color proposals above. IMO, one of our priorities should be avoiding overly harsh contrast on the docs site, but other than that, any color is fine by me!

I also like the blue-and-yellow, if anyone wants my opinion. It's kind of thematic, since it matches the colors of the python logo, and is friendly to most forms of colorblindness (I think? I'm not an expert on accessibility).

- Proper attribution!

Maybe a special line in the readme, after the Authors, to say thanks to @michaelizergit for the logo design?

**Comment by lafrech** [comment]
I agree about avoiding too bright colors. Other than this, all colors suit me.

@michaelizergit it would be nice if you could share the source file for the logo.

**Comment by sirosen** [comment]
When I looked in the middle of last year, it seemed to me that @michaelizergit's account may be defunct? I see very little activity and no commits. I don't want to jump to conclusions, but I was starting to wonder if we should just take and modify the logo as we see fit, then attribute it.

It's his work, but he was offering it up to us, so I think we're okay to take and tweak it.
