### ISSUE TITLE
Keep arg as a str

### ISSUE THREAD

**Issue by bustawin** [marshmallow-code/webargs#318]
Hello,

I have a query field: `.../?search=foo`. This query field must always be a string, however when I do `.../?search=1` the '1' is casted to int, which then Marshmallow dislikes because the field is set as a Str. If I set the field as Raw everything works but the value is then returned to str.

Is there a way to tell webargs to keep it as a str?

Btw, thanks for such amazing library!

**Comment by sloria** [comment]
So I understand correctly: Is the web framework you're using casting to an int when you do `?search=1`? Or is webargs doing that?

**Comment by bustawin** [comment]
Mea culpa. I was casting it wrong, as you suggested. Thank you :-)
