### ISSUE TITLE
TypeError: handle_error() takes exactly 3 arguments (5 given)

### ISSUE THREAD

**Issue by erwinyusrizal** [marshmallow-code/webargs#359]
Hi, I updated webargs with the new version (5.1.0), but I got this error

```
 File "../python2.7/site-packages/webargs/core.py", line 283, in _on_validation_error
    error_handler(error, req, schema, error_status_code, error_headers)
TypeError: handle_error() takes exactly 3 arguments (5 given)
```
it seems the default arguments in `self.error_callback` only has 3 args

https://github.com/marshmallow-code/webargs/blob/1a05a6b61c2a5f8d630e4a6f5d8995d0ede12f36/webargs/core.py#L522

Thanks

**Comment by lafrech** [comment]
Sounds like your error handler needs to be updated due to a change introduced in 4.2.

See https://github.com/marshmallow-code/webargs/blob/dev/CHANGELOG.rst#420-2018-12-27.

The legacy error handlers were supported until 5.0.

**Comment by erwinyusrizal** [comment]
Cool thanks @lafrech
