### ISSUE TITLE
simplejson not installed when installing webargs on Python 2.7

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/webargs#363]
Discovered in: https://github.com/inveniosoftware/invenio-files-rest/pull/185#issuecomment-457940311

We are currently distributing a universal wheel built on Python 3.6 (in Travis). So when the wheel is built, [this conditional is never True](https://github.com/marshmallow-code/webargs/blob/1928c0dd5dfc6db84146b074dcb537092ee16065/setup.py#L7). This results in a wheel that doesn't contain `simplejson` as a dependency on Python 2.7.

One solution would be to distribute different wheels for Python 2 and for Python 3.

**Comment by lafrech** [comment]
> One solution would be to distribute different wheels for Python 2 and for Python 3.

That would be the ideal solution.

If it is too much trouble, we could drop the condition and require simplejson for any Python version. Until we manage to make two different builds or we drop Python 2...

**Comment by sloria** [comment]
This might be as simple as setting `universal = 0` in `setup.cfg` then adding a Travis build stage that runs in a Python 2 environment. I might give this a shot sometime this week.

**Comment by sloria** [comment]
OK, webargs 5.1.1 will now install simplejson when installed with Python 2.
