### ISSUE TITLE
License no longer included in sdist

### ISSUE THREAD

**Issue by mcs07** [marshmallow-code/webargs#364]
This commit https://github.com/marshmallow-code/webargs/commit/f41fb1b7348bc269280bf0c9d44abb3444094692 seems to have resulted in the `LICENSE` file no longer being included in the source distribution on PyPI. As a result, the conda-forge builds are failing: https://github.com/conda-forge/webargs-feedstock/pull/23

**Comment by sloria** [comment]
Ah, so `license_file = LICENSE` must only affect the bdist_wheel but not the sdist.

Ok, I'll look into fixing this for all my projects soon.

Thanks for reporting.

**Comment by sloria** [comment]
OK, release 5.1.1.post0 includes LICENSE in the sdist.
