### ISSUE TITLE
Forgotten error.status_code and error.headers

### ISSUE THREAD

**Issue by decaz** [marshmallow-code/webargs#365]
Despite #327 and #336 there are still `error.status_code` and `error.headers` at several places within the code base.

**Comment by sloria** [comment]
@decaz Where do you see usages of `ValidationError.status_code`?

**Comment by decaz** [comment]
```bash
$ grep -r "error\.status_code" .
./webargs/falconparser.py:            raise LookupError("Status code {0} not supported".format(error.status_code))
./webargs/aiohttpparser.py:            raise LookupError("No exception for {0}".format(error.status_code))
./tests/test_tornadoparser.py:        assert error.status_code == 400
./tests/test_core.py:    assert error.status_code == 418
```

```bash
$ grep -r "error\.headers" .
./tests/test_core.py:    assert error.headers == {"X-Foo": "bar"}
```

**Comment by sloria** [comment]
In those cases, `error` is not a `ValidationError`. They are framework-specific HTTP exceptions.

**Comment by sloria** [comment]
There was one incorrect usage in the docs, which is fixed now.

**Comment by decaz** [comment]
@sloria isn't it `ValidationError` in use in the following methods?
https://github.com/marshmallow-code/webargs/blob/08073eb93e5d2fb54efc8a5aa6f91eea98b8e059/webargs/aiohttpparser.py#L156
https://github.com/marshmallow-code/webargs/blob/08073eb93e5d2fb54efc8a5aa6f91eea98b8e059/webargs/falconparser.py#L154
For `AIOHTTPParser` I see there is https://github.com/marshmallow-code/webargs/blob/08073eb93e5d2fb54efc8a5aa6f91eea98b8e059/webargs/aiohttpparser.py#L141-L143
We can replace them by `error_status_code` variable. And maybe there are also `ValidationError` objects within the test files I got by grep?

**Comment by sloria** [comment]
Ah, I missed those.

I'll fix those and look at the other usages.

Thanks for looking into it.

**Comment by sloria** [comment]
Looks like those two were the only remaining usages. The other matches of your `grep` were for HTTP exceptions.
