### ISSUE TITLE
AttributeError: module 'typing' has no attribute 'NoReturn' with Python 3.5.3

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/webargs#366]
I get this error when running the tests with Python 3.5.3.

```
tests/test_py3/test_aiohttpparser_async_functions.py:6: in <module>
    from webargs.aiohttpparser import parser, use_args, use_kwargs
webargs/aiohttpparser.py:72: in <module>
    class AIOHTTPParser(AsyncParser):
webargs/aiohttpparser.py:148: in AIOHTTPParser
    ) -> typing.NoReturn:
E   AttributeError: module 'typing' has no attribute 'NoReturn'
```

The docs say [`typing.NoReturn`](https://docs.python.org/3/library/typing.html#typing.NoReturn) was added in 3.6.5. However, [the tests pass on Travis](https://travis-ci.org/marshmallow-code/webargs/jobs/486701760) with Python 3.5.6.

**Comment by sloria** [comment]
Looks like this was a bug until 3.5.4rc1 : https://bugs.python.org/issue28556 .

@lafrech Can you upgrade your Python version?

**Comment by lafrech** [comment]
Not really. https://packages.debian.org/search?keywords=python3

I could use pyenv to develop and run the tests. Still, people using Debian stable or any 3.5.3- version can't run the asyncio part of the code. I mean it is not only about me running the tests but also about anyone willing to run an application using the lib.

But as long as no one complains, maybe we can live with this until 3.6 or 3.7 is standard.

**Comment by sloria** [comment]
I see. I'd prefer not to support old patch versions Python, but we can live with removing the `typing.NoReturn` usages for now, at least until we decide to drop 3.5 support.
