### ISSUE TITLE
Re-factor cache invalidation

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/webargs#374]
https://github.com/marshmallow-code/webargs/issues/371#issuecomment-471578852

**Comment by sirosen** [comment]
Is it reasonable to consider removing the cache altogether?
I think that after #420 , it maybe isn't so important to cache the results of parsing.

Alternatively, I would be willing to take a crack at the suggested solution,

> Changing Parser classes into parser class factories, making `use_args`, `use_kwargs`, and perhaps `parse` class methods.

to see if what I come up with is satisfactory.

**Comment by lafrech** [comment]
> Is it reasonable to consider removing the cache altogether?
> I think that after #420 , it maybe isn't so important to cache the results of parsing.

Good point. Is there any interest in keeping a cache, now?
