### ISSUE TITLE
Schema factory function not receiving request?

### ISSUE THREAD

**Issue by antgel** [marshmallow-code/webargs#377]
I'm trying to to implement a schema factory for `PATCH`. In [the docs](https://webargs.readthedocs.io/en/latest/advanced.html#schema-factories), how does `make_user_schema` receive its `request` parameter? Is it automagic? It doesn't work for me in the following configuration (or indeed using the generic helper @use_args_with as explained in the later part of the schema factory docs):

```
# schemas/user.py:

class UserSchema(ma.ModelSchema):
    class Meta:
        model = User
        strict = True

    def make_user_schema(self, request):
        # Filter based on 'fields' query parameter
        only = request.args.get("fields", None)
        # Respect partial updates for PATCH requests
        partial = request.method == "PATCH"
        # Add current request to the schema's context
        return UserSchema(only=only, partial=partial, context={"request": request})

# models/user.py:

class UsersView(FlaskView):
    @use_args(UserSchema.make_user_schema)
    def patch(self, _id, args):
        # cool stuff 
```

Results in `TypeError: make_user_schema() missing 1 required positional argument: 'request'`. I can paste the full stack trace if needed, but I'm not sure it is in this case.

I'm using flask-classful, which may or may not have an impact on this, I don't know enough about the desired behaviour. I opened [this issue on f-c](https://github.com/teracyhq/flask-classful/issues/105) because it's generating the wrong route, but I'm not sure where the cause lies.

**Comment by lafrech** [comment]
I don't know flask-classful.

In webargs, the request object is passed to `parse` (https://github.com/marshmallow-code/webargs/blob/dev/src/webargs/core.py#L458), which passes it to `_get_schema` (https://github.com/marshmallow-code/webargs/blob/dev/src/webargs/core.py#L364) which in turn passes it to your callable (https://github.com/marshmallow-code/webargs/blob/dev/src/webargs/core.py#L314).

Maybe you could debug that by installing webargs locally and adding a few prints to see what happens.

**Comment by antgel** [comment]
Thanks for responding, it was very helpful. After a while getting in deep, it was a problem (actually two) with flask-classful. Followed up on https://github.com/teracyhq/flask-classful/issues/105, PR https://github.com/teracyhq/flask-classful/pull/106.
