### ISSUE TITLE
Any way to skip validation altogether for an empty string?

### ISSUE THREAD

**Issue by ThiefMaster** [marshmallow-code/webargs#380]
In my schema I have this field:

```
tileserver_url = fields.String(validate=[
    validate.URL(schemes={'http', 'https'}),
    lambda value: all(x in value for x in ('{x}', '{y}', '{z}'))

])
```

Generally this works fine, but if I send an empty string (because it's optional) then validation still fails. Sending `null` is not really an option since then I'd not only have to change the client-side code to convert `''` to `null`, but also the  server-side code after parsing the data to convert `null` back to `'`'...

I wonder if there's any way to skip validation for empty strings on the webargs level or if I really have to subclass `StringField` to do that...

**Comment by lafrech** [comment]
Not an answer to your empty string issue but in case you didn't notice, there is a `URL` field you could use.

What marshmallow version are you using (2.x or 3rc)?

**Comment by ThiefMaster** [comment]
MM 3 - and good point (url field instead of string)

**Comment by lafrech** [comment]
Do you really want to store an empty string?

Otherwise, please see related discussions

- https://github.com/marshmallow-code/marshmallow/issues/583
- https://github.com/marshmallow-code/marshmallow/issues/713

**Comment by ThiefMaster** [comment]
Yeah, saw those.. I hoped there'd be a better option but after looking at the code it looks like it's either subclassing or switching to None
