### ISSUE TITLE
Help needed to validate the request parameter based on another parameter?

### ISSUE THREAD

**Issue by kalidassweb** [marshmallow-code/webargs#381]
```
class Collection(object):
    @staticmethod
    def on_get():
        return {
            'user_id': fields.Str(missing=None,validate=Validators.url_id_exists),
            'group_id': fields.Str(missing=None,validate=Validators.group_id.exists),
        }

```

```
  @use_args(Validation.Collection.on_get(), locations=('query', 'json','view_args'))
   def on_get(self, req, resp, args):{
```

in this above code case, I like to validate the 

if user_id missing group_id required

if group_id missing user_id required

In documentation, I don't find any options

**Comment by lafrech** [comment]
Search for "schema level validation" in marshmallow docs (and bugtracker, and perhaps also on SO).

**Comment by sloria** [comment]
Yes, you probably want to pass a schema to `use_args` and use `@validates_schema`: https://marshmallow.readthedocs.io/en/3.0/extending.html#schema-level-validation
