### ISSUE TITLE
Pre-processing should occur before type conversion

### ISSUE THREAD

**Issue by ewang** [marshmallow-code/webargs#4]
Currently, the Arg#use callable is called after type conversion. I think it would be more useful if called prior to type conversion.

Example: self.type(self.use(...)) instead of self.use(self.type(...))

**Comment by sloria** [comment]
Can you elaborate on your rationale and give an example use case?

**Comment by ewang** [comment]
This way one can use the Arg#use callable as a way of modifying the input value before being type converted.

My current use case is if the input argument is a blank string, I get an error since int() can't parse a blank string. In such a case it might be useful to be able to return 0 or some other value before parsing.

Perhaps a better implementation would be the addition of a flag (i.e. allow_error=True) that would simply suppress parsing errors and set it to the value specified for Arg#default

**Comment by sloria** [comment]
After thinking this over, I think you make a valid point; preprocessing will necessarily have to occur before type conversion in some instances. Another common case will be datetime strings, which must be parsed before being converted to a datetime object.

**Comment by sloria** [comment]
I've gone ahead with the change, so I'm closing this. Adding the `allow_error` parameter is another issue that I will have to think about. 

Thanks for the suggestions!
