### ISSUE TITLE
parse_json fails and returns 400 when data POST in form

### ISSUE THREAD

**Issue by mozartilize** [marshmallow-code/webargs#409]
currently I have an `@use_args(LoginSchema(), locations=("json", "form"))`

If I post data in form, the code will fail to parse json and return 400 status code instead of looking in form data

**Comment by sloria** [comment]
Which framework are you using? Does the issue still occur if you switch the order of "json" and "form"?

**Comment by mozartilize** [comment]
I'm using Flask, it's works if I change the order in locations

**Comment by sloria** [comment]
Ah, this is expected behavior. Locations get parsed in order. When parsing `json`, the parser will attempt to JSON-decode the payload and return a 400 for invalid JSON. Therefore, you should attempt to parse form data before parsing JSON.
