### ISSUE TITLE
Parsed arguments in Python 3.x w/ Tornado are bytestrings instead of unicode

### ISSUE THREAD

**Issue by thomasboyt** [marshmallow-code/webargs#41]
I ran into some unexpected behavior using this library with Tornado in Python 3.x. It's easy to see using the hello world example:

``` python
import tornado.ioloop
from tornado.web import RequestHandler
from webargs import Arg
from webargs.tornadoparser import use_args

class HelloHandler(RequestHandler):
    """A welcome page."""

    hello_args = {
        'name': Arg(str, default='Friend')
    }

    @use_args(hello_args)
    def get(self, args):
        response = {'message': 'Welcome, {}!'.format(args['name'])}
        self.write(response)


if __name__ == '__main__':
    app = tornado.web.Application([
        (r'/', HelloHandler),
    ], debug=True)
    app.listen(5001)
    tornado.ioloop.IOLoop.instance().start()
```

Querying `localhost:5001?name=foo` will result in the output:

```
{"message": "Welcome, b'foo'!"}
```

This is because Tornado's arguments are bytestrings in Python 3.x, and casting them to `str` causes them to be in the form `b'<val>'`. 

There are a few ways to fix this behavior. The easiest, requiring no actual code change, is to just use `tornado.escape.to_unicode`:

``` python
from tornado.escape import to_unicode

hello_args = {
    'name': Arg(to_unicode, default='Friend')
}
```

This results in the output you'd expect, and is reasonable enough, though I believe this should be documented if it's the recommended way to use this library with Tornado in Python 3.x. 

Alternatively, `get_value` in `tornadoparser.py` could be updated to use Tornado's `get_argument` methods, which automatically decode to unicode: http://tornado.readthedocs.org/en/latest/web.html#input. This would mean any custom converter method would be passed a regular (unicode) string instead of a bytestring, which may be preferred.

**Comment by sloria** [comment]
Thanks @thomasboyt . I think using `get_argument` is probably the right direction, as it meets the most common use case.

Pull requests welcome!

**Comment by sloria** [comment]
This should now be fixed by virtue of using marshmallow's `field.Str()` rather than `Arg(str)`. That said, it appears that `get_query_argument` and `get_body_argument` are the preferred way to access request input, so I still think it's a good idea to change the implementation in `TornadoParser` to be consistent with those.

**Comment by sloria** [comment]
Arguments are now decoded to unicode strings. Thanks again for the suggestion.
