### ISSUE TITLE
Schema factory only variable fail - can't pass list type

### ISSUE THREAD

**Issue by antgel** [marshmallow-code/webargs#412]
Looking at the [schema factory docs](https://webargs.readthedocs.io/en/latest/advanced.html#schema-factories), I'm interested in trying the
```
# Filter based on 'fields' query parameter
only = request.args.get("fields", None)
```
part.

However, when I try appending something like `?fields=some_field` to my HTTP request, I get the following error:
```
File "edited/marshmallow/schema.py", line 349, in __init__
    raise StringNotCollectionError('"only" should be a list of strings')
```

As far as I can see, webargs always passes the query string parameters as strings. I tried wrapping it in square brackets, but I think I'm barking up the wrong tree. Have I misunderstood something, or is this a bug?

**Comment by sloria** [comment]
It's possible the docs are incorrect. `only` does need to be a collection of strings, but `request.args.get` will return a string. Can you try using `request.args.getlist('fields')` instead?

**Comment by sloria** [comment]
Actually, if you want to use a comma-delimited list for `fields`, you'd do the following:

```python
def make_user_schema(request):
    # Filter based on 'fields' query parameter
    fields = request.args.get("fields", None)
    only = fields.split(",") if fields else None
    # Respect partial updates for PATCH requests
    partial = request.method == "PATCH"
    # Add current request to the schema's context
    return UserSchema(only=only, partial=partial, context={"request": request})
```

The docs will be updated in a moment.

**Comment by antgel** [comment]
Thanks @sloria , I had seen your previous response and was about to implement something similar. 

I'd like to ask about the use case for this. I have a many-to-many relationship between `Survey` and `Answer` in my database. I might want to indicate that `Survey` 123 was answered with `Answer` 456 with an API call (Flask-Classful) such as:

`http PUT http://localhost:5000/surveys/123/answer/ answer_id=456`

If I don't add `fields`, i.e.

`http PUT http://localhost:5000/incidents/10/answer/?fields=answer_id answer_id=1`

I get a 422 Unprocessable Entity because I'm not supplying a value for `survey_id`. Is this a sane use case for `fields`, or am I doing something wrong in my design? Here's some code that should hopefully give some background info.

```python
class SurveyAnswer(AssociationModel):
    survey_id = db.Column(db.Integer, db.ForeignKey("survey.id"), primary_key=True)
    answer_id = db.Column(
        db.Integer, db.ForeignKey("answer.id"), primary_key=True
    )

    survey = db.relationship("Survey", backref=backref("survey_answers"))
    answer = db.relationship("Answer", backref=backref("answer_surveys"))

class SurveyAnswerSchema(ma.ModelSchema):
    class Meta:
        include_fk = True
        model = SurveyAnswer

class SurveysView(FlaskView):
    @use_args(SurveyAnswerSchema)
    @route("/<id>/answer/", methods=["PUT"])
    def answer(self, args, id):
        survey = Survey.query.get_or_404(id)
        answer = Answer.query.get_or_404(args.answer_id)
        sa = SurveyAnswer(
            survey=survey, answer=answer
        )
        db.session.commit()
        return "", 200
```

Please let me know if what I'm asking isn't clear, thanks. :)
