### ISSUE TITLE
Use case for `fields` in schema factory - many to many?

### ISSUE THREAD

**Issue by antgel** [marshmallow-code/webargs#418]
I'm following up from #412 , I guess my last comment there wasn't seen because the issue was closed.

I'd like to ask about the use case for this. I have a many-to-many relationship between `Survey` and `Answer` in my database. I might want to indicate that `Survey` 123 was answered with `Answer` 456 with an API call (Flask-Classful) such as:

`http PUT http://localhost:5000/surveys/123/answer/ answer_id=456`

If I don't add `fields`, i.e.

`http PUT http://localhost:5000/incidents/10/answer/?fields=answer_id answer_id=1`

I get a 422 Unprocessable Entity because I'm not supplying a value for `survey_id`. Is this a sane use case for `fields`, or am I doing something wrong in my design? Here's some code that should hopefully give some background info.

```python
class SurveyAnswer(AssociationModel):
    survey_id = db.Column(db.Integer, db.ForeignKey("survey.id"), primary_key=True)
    answer_id = db.Column(
        db.Integer, db.ForeignKey("answer.id"), primary_key=True
    )

    survey = db.relationship("Survey", backref=backref("survey_answers"))
    answer = db.relationship("Answer", backref=backref("answer_surveys"))

class SurveyAnswerSchema(ma.ModelSchema):
    class Meta:
        include_fk = True
        model = SurveyAnswer

class SurveysView(FlaskView):
    @use_args(SurveyAnswerSchema)
    @route("/<id>/answer/", methods=["PUT"])
    def answer(self, args, id):
        survey = Survey.query.get_or_404(id)
        answer = Answer.query.get_or_404(args.answer_id)
        sa = SurveyAnswer(
            survey=survey, answer=answer
        )
        db.session.commit()
        return "", 200
```

Please let me know if what I'm asking isn't clear, thanks. :)

**Comment by sloria** [comment]
The use case for `fields` in the docs is for when you want to implement something like [sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets), i.e. allow the client to request a subset of fields.

I'm not sure  what you're asking here. Can you clarify?

**Comment by antgel** [comment]
@sloria Sorry for the slow response, I've been travelling. First and foremost, I didn't know that JSON:API existed. I will surely take a look at that, as it might solve some of my design conundrums. Thank you.

So `fields` is generally to make a `GET` request more specific. I'll explain more about my use case, although I'm not sure how to do so, I'll try.

Take an app in which the user answers questions, let's say a Survey Monkey clone (it's not, but let's say it is). Also I'll use the term `Question` instead of the confusing `Survey` that I used above.

The `Question` table contains the following questions:
```
ID  question
1 What is your favourite animal?
2 What is your favourite colour?
```

The `Answer` table contains the following answers, `question_id` being a foreign key into `Question`.
```
ID answer question_id
1  Dog    1
2  Cat    1
3  Parrot 1
4  Red    2
5  Green  2
6  Blue   2
```

I have a link many-to-many table `QuestionAnswer` with fields `question_id` and `answer_id`.

Let's say a user indicates their favourite colour (question 2) is red (answer 4). This means I'll want to finish up with `INSERT INTO QuestionAnswer (question_id, answer_id) VALUES (2, 4);`.

(`http` in the following is [httpie, the command line http client](https://httpie.org).)

It will translate into an API call something like:
`http PUT http://localhost:5000/questions/2/answer/ answer_id=4`

If I add the fields `fields` parameter, it works:
`http PUT http://localhost:5000/questions/2/answer/?fields=answer_id answer_id=4`

But if I don't add `fields`, I get a 422 Unprocessable Entity because I'm not supplying a value for `question_id`.

*Is this a sane use case for `fields`, or am I doing something wrong in my design? If not, should I be using `partial` for this kind of update?* The `use_args_with` example code sets `partial = True` only for `PATCH`, not `PUT`, yet it does work when I allow `partial = True` for `PUT` as well.

I don't want to run ahead like this because I'm concerned that I might be doing something "bad", either in my API design or in my application.

The schema, model, and controller are in the original thread (just think "question" instead of "survey").

Does that help? If not, please let me know what isn't clear and I'll elaborate. :)

**Comment by antgel** [comment]
Update, issue solved thanks to sage advice from @sloria .

The issue is that conceptually, despite my widespread use of marshmallow-sqlalchemy's `ModelSchema`, many REST API endpoints require a `Schema` tailored to the parameters, rather than tailored to the underlying tables.

This manifested itself in use of the incorrect `SurveyAnswerSchema`. The correct approach was to instead create a new schema, `SurveyAnswerPutSchema`, with a single `answer_id` field, and everything works as intended.

Perhaps this is obvious to many users, but it wasn't to me.
