### ISSUE TITLE
RFC: Only accept delimited string in DelimitedList

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/webargs#423]
`DelimitedList` accepts either a list or a delimited string (e.g. "foo,bar,baz").

I'd like to make it more strict by only accepting a delimited list. Rather than adding a `strict` parameter, I'm thinking of dropping the whole "also accept a list" feature.

Any reason to support both?

I understand it inherits from `List` because once the string is parsed, it can be deserialized as a normal list. But are there cases where you'd expect either a list or a delimited string?

**Comment by sloria** [comment]
I don't have a strong opinion either way. `DelimitedList` is typically used for parsing query params, in which case the input will always be a string. So perhaps it makes sense to only allow delimited strings.
