### ISSUE TITLE
Add missing 5.5.2 git tag

### ISSUE THREAD

**Issue by koobs** [marshmallow-code/webargs#445]
Repository tag for the 5.5.2 release (per PyPI sdist) is missing. Please add it corresponding to the commit that the source distribution was based on. Thanks!

**Comment by sloria** [comment]
I see it here: https://github.com/marshmallow-code/webargs/releases/tag/5.2.2 . The sdist is here. Am I missing something? https://pypi.org/project/webargs/5.5.2/#files

**Comment by koobs** [comment]
@sloria 5.(5).2 is missing, 5.(2).2 was tagged October 6. I'm guessing it was a typo.

![2019-12-18 11_57_26-marshmallow-code_webargs_ A friendly library for parsing HTTP request arguments,](https://user-images.githubusercontent.com/1011612/71046870-9c713380-2131-11ea-81bf-69a54bfb02b8.png)

**Comment by sloria** [comment]
Ah, yes it was a typo. I've just pushed up 5.5.2. Thanks for reporting.

**Comment by koobs** [comment]
@sloria You're welcome :)
