### ISSUE TITLE
Combine errors from nested `use_args` calls so that mixed locations still provide full errors in webargs 6.x

### ISSUE THREAD

**Issue by sirosen** [marshmallow-code/webargs#455]
> Won't we need to merge error messages for the stacked case?
>
> ```python
> @use_args({"related_id": fields.Str(required=True))}, location="query"})
> @use_args({"name": fields.Str(required=True))}, location="json")
> ```
>
> ```python
> {"related_id": ['Missing...'], "name": ["Missing..."]}
> ```

_Originally posted by @sloria in https://github.com/marshmallow-code/webargs/issues/419#issuecomment-525765453_

Supporting this is desirable, since otherwise you only get partial information about validation failures. IMO, the worst part is this: the behavior depends on the order of your `use_args` calls.

I've been thinking about this only a little bit since that issue and I think what's best is that `use_args` calls stash their arguments somewhere and then process them "all at once" before the user-supplied function.

One potential implementation path:
- `use_args` adds its arguments to some private attribute of the decorated function like `func.__webargs_use_args_schemas` (initialized as an empty list)
- the _innermost_ `use_args` call walks all of the `__webargs_use_args_schemas` data and evaluates _all of it_ capturing and combining any `ValidationError`s
- outer `use_args` calls add data to the "schema list" but return the function they were given without trying to do any parsing
  - we could detect this by having the innermost `use_args` set a flag like `__webargs_is_use_args_wrapped` which we check with `hasattr`

I'd also like to explore whether or not it would be safe to replace the `use_args` callable with a callable object of our own design. That might make the implementation simpler than proposed above, but I'm not sure if it will work with all frameworks.

Some questions:
1. Is this actually a good idea? Just because we _can_ do this and it would be nice for users doesn't mean that it's worth the complexity. I'm worried that I'm looking at what's **possible** rather than what's **wise**.
2. Is there a better way to do this than storing decorator arguments in a list?
3. Once you've done a bunch of parsing and have multiple `ValidationError`s in hand, what's the correct way to combine them?

**Comment by lafrech** [comment]
I'm afraid it could be too complicated for the benefit.

And I don't think it is *that* bad if we don't do it.

I'm open to the idea if it is possible but let's keep things simple.

**Comment by sirosen** [comment]
After cooling off for a few days, I agree that what I put forth above is too complicated. I haven't started on this because every time I sit down to do any work on it, there seem to be problems or concerns about at least one supported framework.

I'm still trying to think of other ways to collect multiple errors, however.

For example, are things like
```python
@webargs.use_args_by_location({
    "query": {"related_id": fields.Str(required=True)},
    "json": {"name": fields.Str(required=True)}
})
def viewfunc(*args, **kwargs):
    ...
```
worth considering?

I think a part of the question is how much concern there is about the original case put forth by @sloria . If it's okay to ignore for 6.0.0, it's always possible to add some new usage or new methods which address it in the future.

But if we want to make `use_args` do it internally, it might be hard to do without making it part of 6.0.0 -- it's the only time, near-term, when we can further tweak the signature of `use_args` if necessary.

**Comment by lafrech** [comment]
I don't understand.

Isn't the whole issue about @sloria's comment (nested `use_args` calls use case)?

**Comment by sirosen** [comment]
Sorry, I should have clarified what I'm asking:

If it's too hard or messy to make the nested `use_args` case work, is it even worth considering some other usage or solution which can more easily handle parsing multiple locations and combining the errors?

I can come up with alternatives to `use_args` which do the same work and handle this case, but I'm not sure it's even worth taking the time to talk about / think about such things.

**Comment by lafrech** [comment]
Oh, you mean it may be too hard to let `use_args` do that but we could come up with another decorator that would do the two calls in one go so that we have the information about the schemas in the same decorator. Like the `use_args_by_location`.

Frankly, I wouldn't bother. As [I said](https://github.com/marshmallow-code/webargs/issues/419#issuecomment-525771078):

> I don't see an easy way to provide all the errors at once. But it's not a big deal if we don't IMHO.
> 
> It's like sometimes input data passes webargs validation and then triggers an error in the view func (e.g. unique index issue in DB), so a new error message appears.

From a security perspective, the app is covered. It's all about client-friendliness. It's nice to be able to return all errors from a JSON input at once rather than one by one, as the cardinality could go high. But dealing with query args first then JSON is not a big issue to me. Assuming two, three nested calls at worse, that's still a reasonable figure for a trial and error approach. Typically, only the body has a lot of fields.

**Comment by sirosen** [comment]
I worked up a version of this and concluded that it's _definitely_ not worth the trouble. Even if you modify `use_args` to put parameters into a list, which turns out not to be so bad, you have to start tinkering with the way that `Parser.parse_args` works too (to skip calling the error handler function).

I can get it all working, but it's not worth making things that much messier and harder to maintain.

> Assuming two, three nested calls at worse, that's still a reasonable figure for a trial and error approach. Typically, only the body has a lot of fields.

Ultimately, this convinced me. I think you're right.

@lafrech, thanks for taking the time to read this and talk about it. I'm going to close as a wontfix and look at other things which are worth doing for 6.0.
