### ISSUE TITLE
Wrong version number 6.6.0b1 instead of 6.0.0b1 🤦

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/webargs#457]
@sloria, I typoed while bumping version number. I set 6.6.0b1 instead of 6.0.0b1.

Althought it is bad practice to delete releases once they are released, since this is a beta version, I would have deleted it from PyPI and published a bugfix release. Except I don't have required credentials to delete the wrong release on PyPI.

How should we proceed? Can you delete the wrong release and I publish a 6.0.0b2?

Sorry about that. Good thing it was just a pre-release.

I use bumpversion on other projects and it provides an additional safety net. I did double or triple check before pushing but I didn't see that.

**Comment by sloria** [comment]
No problem. I deleted 6.6.0b1 and reuploaded 6.0.0b1.

I'm not opposed to bumpversion. IIRC I didn't add it because it seemed like more configuration and opinions than it was worth. But I suppose it would avoids human error. Feel free to add it if you'd like.

**Comment by lafrech** [comment]
I use it on flask-smorest and umongo. It does raise config questions and issues. Overall I'm happy with it. Even if I double-check everytime after using it.

I'd rather keep webargs aligned with marshmallow, apispec, and all. I always refer to RELEASING file in marshmallow before releasing. So until we want to use bumpversion on all repos, I won't add it here. I agree. Open to it but not sure it is worth it.
