### ISSUE TITLE
[RFC] Namespace error structures by location in response

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/webargs#460]
I think there's a case we never really considered: two schemas in a different location with a common field name.

In webargs 5, this is not possible in a single `use_args` call. In a multi `use_args` call, it depends if the user specifies the locations. The response is ambiguous about which field is wrong.

In current implementation in webargs 6, the response is ambiguous. A way to fix this would be to namespace the error structures by location.

Just thinking out loud, writing this here before I forget.

**Comment by sirosen** [comment]
Were you thinking something like these structures, with the location as a top-level namespace for the error messages?
```json
{"body":{"foo":["Not a valid integer."]}}
{"query":{"bar":["Not a valid list."]}}
```

I'm looking at maybe doing this by rewriting the error messages in `Parser._on_validation_error`. Does that seem like a good idea? I'm also looking a bit at how we could change the error messages when `Schema.load` gets called, but I'm not seeing a way.

**Comment by lafrech** [comment]
Yeah, that's it. I should have added an example.

I didn't take the time to investigate how we could do that yet. Just wondering out loud about the benefit of doing it.

**Comment by sirosen** [comment]
I've put together a PR with the solution put forth above, but it's making me wonder more about whether or not it would be better for webargs to put `location` in some other field.

Largely, what I'm wondering about is this:

Should there instead be
- `WebargsValidationError` inheriting from `marshmallow.ValidationError`
- `WebargsValidationError.location` is a new attribute, separate from `messages`
- `Parser._on_validation_error` re-wraps error data in a `WebargsValidationError` and passes that to the error handler

?

Modifying `messages` in-place is definitely simpler, but will we trip people up unnecessarily by doing so?

**Comment by lafrech** [comment]
Where (in which method) would WebargsValidationError.location be set? Where would it be read and where would the messages dict be modified?

I think I see what you mean but I don't see where this would happen, or which use case is prevented in your current implementation.

Also, you're using the "raw" location (the key in location_map). We could use the unified location (values in the mapping), but on second thought it is more flexible the way you did it as the user can define his own location strings.

**Comment by lafrech** [comment]
Adding this to 6.0.0 milestone so that we don't forget to decide on this before shipping.

It can be rejected or even postponed.

**Comment by sirosen** [comment]
> Where (in which method) would WebargsValidationError.location be set? Where would it be read and where would the messages dict be modified?

I think it would be a lot like what I put forth in #463 . In `_on_validation_error`, instead of doing
```python
error.messages = {location: error.messages}
```
I'm considering
```python
# does expanding error.args like this even work? I haven't tested
error = WebargsValidationError(*error.args, location=location)
```

> I don't see ... which use case is prevented in your current implementation.

#463 is fine, but I'm wondering if it might make things harder for someone who has existing error handler code that looks at the messages.

6.0 is a major release so it's not a big deal. We can ask people to tweak their code appropriately.

> Also, you're using the "raw" location (the key in location_map)? We could use the unified location (values in the mapping), but on second thought it is more flexible the way you did it as the user can define his own location strings.

I have no strong feeling on this. Using `self.__location_map__.get(location)` would be fine, IMO. I'd expand it out into
```python
loc_name = self.__location_map__.get(location)
if inspect.isfunction(loc_name):
    loc_name = location
```
to be safe.

On the one hand, it's kind of nice that if a user passes `location="query"`, their errors will come back with `"query": ...` and if they pass `location="querystring"`, their errors come back with `"querystring": ...`. So we're "respecting the user's preferred naming".
On the other hand, it sucks that if you're working in a big team, one person might write "query" and another person might prefer "querystring". So you end up with an apparent inconsistency that way.

If you have a preference, let me know. I'm happy to make the above change.

**Comment by lafrech** [comment]
From [OpenAPI spec](https://swagger.io/specification/):

> The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location.

In OpenAPI, for instance, it is totally valid to have the same param name in different locations, so without the namespacing, we can have name clashes.

I don't see this issue as important or urgent, but overall, I think it would be a nice fix.

> On the one hand, it's kind of nice that if a user passes location="query", their errors will come back with "query": ... and if they pass location="querystring", their errors come back with "querystring": .... So we're "respecting the user's preferred naming".
On the other hand, it sucks that if you're working in a big team, one person might write "query" and another person might prefer "querystring". So you end up with an apparent inconsistency that way.
> 
> If you have a preference, let me know. I'm happy to make the above change.

Well I think it is better this way. More flexible. I was just mentioning it in case you didn't really think of it. I thought it was better to discuss it and decide it on purpose. But it is better this way.

About `WebargsValidationError`, it is still unclear to what the difference would be and why choose an option over the other.

**Comment by sirosen** [comment]
> I don't see this issue as important or urgent, but overall, I think it would be a nice fix.

I mostly agree, but I think we're free to make changes to the `messages` field now (in 6.0) which we can't do later without another major release. So I'd like to decide this before v6 is finished.

> Well I think it is better this way [using the caller's `location` value]. More flexible. I was just mentioning it in case you didn't really think of it. I thought it was better to discuss it and decide it on purpose. But it is better this way.

👍 Cool. I didn't really think about it before, so if you're happy with what's in #463, so am I.

> About `WebargsValidationError`, it is still unclear to what the difference would be and why choose an option over the other.

Creating a new error class with `location` in a separate field is what I would do if I wanted to make this change in a minor release. Changing `messages` is a backwards incompatible change for anyone parsing that field's contents.

<details><summary>here's a simple example app which parses the messages</summary>

```python
import marshmallow as ma
from webargs.flaskparser import FlaskParser

import flask
from werkzeug.exceptions import BadRequest
from werkzeug.serving import run_simple

parser = FlaskParser()


@parser.error_handler
def handle_webargs_error(error, request, schema, status_code, headers):
    messages = []
    for field, field_messages in error.messages.items():
        messages.append(f"{field}: {field_messages[0]}")
    message = ", ".join(messages)
    raise BadRequest(description=f"Request failed input validation. {message}")


app = flask.Flask(__name__)


@app.route("/")
@parser.use_args({"foo": ma.fields.Int()}, locations=("query",))
def fooroute(foo):
    return {"foo": foo}


run_simple("localhost", 5000, app)
```
</details>

If we rewrite the `messages` field in 6.0, then we're asking anyone with such an error handler to rewrite it.

I don't think this kind of rewrite would be hard for anyone unless they're doing very exotic/complex stuff. And in that case, they might not want to rush to v6.0 anyway.

---

After writing a concrete example of something parsing `messages`, I feel less need to try to avoid changing it. Users could ignore the change by just traversing one level of the `messages` dict, if they so choose, and it's really not that different to have the information there vs in another attribute of the exception.

Given the original suggestion was for the version in #463, let's just go with that?
