### ISSUE TITLE
Checking for argument that is a list of 'int'

### ISSUE THREAD

**Issue by rajatkhanduja** [marshmallow-code/webargs#48]
I was trying to define a nested Arg that allows one of the parameters to be a list of 'int'. While `Arg(list)` only checks if it is of type `list`, I was able to get the necessary validation to work by using `multiple=true` as `Arg(int, multiple=true)`. This gives me a list of int and rejects other types like str. 
However, looking at the [relevant code](https://github.com/sloria/webargs/blob/dev/webargs/core.py#L273), I am not sure if this is the way it's expected to be used. Could you clarify this? If this is an unexpected behavior or something that won't be maintained or guaranteed, is there another way to achieve this?

**Comment by sloria** [comment]
@rajatkhanduja `Arg(int, multiple=True)` is the correct usage. `multiple=True` is used for collections (lists and tuples) and the `type_` argument is used for conversion/validation of _each_ item in the collection.

**Comment by rajatkhanduja** [comment]
Thanks for the clarification :)
