### ISSUE TITLE
How get the value of ValidationError when I used decorator of webargs in Djando whith Class-based Views?

### ISSUE THREAD

**Issue by DesKevinMendez** [marshmallow-code/webargs#490]
I trying get the error of exception validationError, but, i could not capture this info.

I have been to reading the documentation, explicity to django support, since it always returns error 500, when in the documentation it tells me that error 422 would return.

My class of marshmallow

`class CategorieSchema(Schema):
    categorie = fields.Str(validate=validate.Length(min=3), required = True)
 `

My class based view

`
class CategorieListPostGet(APIView):
    
     ....
    
    @use_kwargs(CategorieSchema())
    def post(self, request, **kwargs):

        data = CategoriaSerializer(data=kwargs)

        if data.is_valid():
            data.save()
            return Response(data.data, status=status.HTTP_201_CREATED)

        return Response(data.errors, status=status.HTTP_400_BAD_REQUEST)
            
        `

My serializer

`
class CategoriaSerializer(serializers.ModelSerializer):
    id = serializers.PrimaryKeyRelatedField(read_only=True)
    class Meta:
        model = Categoria
        fields = ("id", "categorie",)
`

Info send from postman:

> {
	"categories": "Postman",
}

My response whith exist any error
`raise exc
marshmallow.exceptions.ValidationError: {'categorie': ['Missing data for required field.'], 'categories': ['Unknown field.']}
[19/Mar/2020 13:03:01] "POST /api/1.0/categoria/ HTTP/1.1" 500 18297`

I haven't understood how do to get this error in my response, but it always return me error 500.

What am I doing wrong?

By the way, I use Django-rest-framework.

**Comment by sirosen** [comment]
@DesKevinMendez, could you tell me where in the docs you're seeing mention of 422s as the expected response? That's true of some of the parsers (Flask, at least), but if you look at the Django Parser docs, we state that it doesn't set an error handler by default:
https://webargs.readthedocs.io/en/latest/framework_support.html#django

If something is saying that all parsers return a 422 validation error by default, that's incorrect and we should fix it.

I also think we should add an example of this, but you don't need to do the type of handling shown in the Django support section of the docs. You can use the `@parser.error_handler` decorator to register a custom error handler which will be called on `ValidationError`s:
https://webargs.readthedocs.io/en/latest/api.html#webargs.core.Parser.error_handler

**Comment by sirosen** [comment]
I'm going to close this because I think it was a misunderstanding of the docs.
I'm not saying that the docs are perfect, or that we shouldn't maybe look at making the support for various frameworks more uniform. But it's not clear to me what the improvements we should make are, based on this.
