### ISSUE TITLE
Missing data for required field error even when data passed in

### ISSUE THREAD

**Issue by odiyan** [marshmallow-code/webargs#492]
I am using python3.7 and flask-restful and webargs to build an api. The endpoint `list-keydates` returns `vesselname: missing data for required field` when I query it with a value for `vesselname`. I think there are a few similar issues listed but don't quite know if it's the same as any of those.

    from flask import Flask, jsonify
    from flask_restful import Api, Resource
    from webargs import fields
    from webargs.flaskparser import use_args, use_kwargs, parser, abort

    app = Flask(__name__)
    api = Api(app)
    
    class KeydateList(Resource):
        keydate_args = {"vesselname": fields.Str(required=True)}
    
        @use_args(keydate_args)
        def get(self, args):
            intervention_list = []
            keydate_list = []
            s = select([keydate.c.Intervention, keydate.c.Date])
            s = s.where(keydate.c.VESSEL==args["vesselname"])
            rp = connection.execute(s)
            for row in rp:
                intervention_list.append((row[0]))
                keydate_list.append((row[1]))
            return jsonify({"keydates": keydate_list,
                            "intervention": intervention_list})
    
    @parser.error_handler
    def handle_request_parsing_error(err, req, schema, error_status_code, error_headers):
        """webargs error handler that uses Flask-RESTful's abort function to return
        a JSON error response to the client.
        """
        abort(error_status_code, errors=err.messages)
    
    
    api.add_resource(KeydateList, '/list-keydates')
    
    if __name__ == '__main__':
        app.run(debug=True)

**Comment by lafrech** [comment]
By default in webargs 6, only json/body is parsed. If vesselname is passed as query argument, you must specify it.

```py
    @use_args(keydate_args, location="query")
```

**Comment by odiyan** [comment]
Thank you, that was it.
