### ISSUE TITLE
Nested in Nested post args not working as expected. 

### ISSUE THREAD

**Issue by venix** [marshmallow-code/webargs#494]
Not sure how to display this properly so here it is: 

https://pastebin.com/GUAxc98c

I am parsing post args for a POST request as follows: 
```
post_args = {
  'item_1': input_fields.Str(),
  'item_2': input_fields.Str(), 
  'item3: input_fields.Nested({
      '0.00': input_fields.Nested({'someItem': input_fields.Str(), ... }),
       '0.10': input_fields.Nested({'someItem': input_fields.Str(), ... }),
       '0.20': input_fields.Nested({'someItem': input_fields.Str(), ... })
  })
}
```
When parsed I expect to get the following: 
```
parsed_args = {
  'item1' : 'some string', 
  'item2': 'some other string',
  'item3': { 
     '0.00': {'someItem': 'some useful string'},
     '0.10': {'someItem': 'some useful string'},
     '0.20': {'someItem': 'some useful string'}
  }
}
```
But instead it puts item3 nested values into a dictionary with key 0 and then the nested items as follows: 

```
parsed_args = {
  'item1' : 'some string', 
  'item2': 'some other string',
  'item3': { 
     '0': {
           '0.00': {'someItem': 'some useful string'},
           '0.10': {'someItem': 'some useful string'},
           '0.20': {'someItem': 'some useful string'}
      }
  }
}
```
Am I doing something wrong? Am I missing anything ? Is this supposed to happen? 

I can confirm that the data received in JSON are in the right structure. 

Any ideas?

**Update** 
I ve noticed this happens when the keys are strings of decimals i.e 0.00 0.10 0.20 but still why can't I do that?

**Comment by lafrech** [comment]
Looks like this is due to marshmallow interpreting the dot in the decimal string as a subpath delimiter.

I'm not sure this behaviour is correct, so it might be a bug.

You might be able to circumvent it by setting a name without dot and using attribute/data_key to get back your dotted name, but that's not ideal.

Untested code:

```py
- '0.00': input_fields.Nested({'someItem': input_fields.Str(), ... })
+ '000': input_fields.Nested({'someItem': input_fields.Str(), ... }, attribute="0.00", data_key="0.00")
```

**Comment by venix** [comment]
> Looks like this is due to marshmallow interpreting the dot in the decimal string as a subpath delimiter.
> 
> I'm not sure this behaviour is correct, so it might be a bug.
> 
> You might be able to circumvent it by setting a name without dot and using attribute/data_key to get back you dotted name, but that's not ideal.
> 
> Untested code:
> 
> ```python
> - '0.00': input_fields.Nested({'someItem': input_fields.Str(), ... })
> + '000': input_fields.Nested({'someItem': input_fields.Str(), ... }, attribute="0.00", data_key="0.00")
> ```

Yeah, I m just setting another name for now, but strange that is being interpreting it like this. I ll give it a shot in what you are suggesting. 

Cheers, 
Michael

**Comment by lafrech** [comment]
I'm afraid my workaround above will work and the issue is the dot in the input data.

Related marshmallow issue : https://github.com/marshmallow-code/marshmallow/issues/1506.

**Comment by venix** [comment]
> I'm afraid my workaround above will work and the issue is the dot in the input data.
> 
> Related marshmallow issue : [marshmallow-code/marshmallow#1506](https://github.com/marshmallow-code/marshmallow/issues/1506).

Great thank you for your input, I can live with the workaround until is resolved.

**Comment by lafrech** [comment]
I meant "I'm afraid my workaround above will not work".
