### ISSUE TITLE
Flask Parser cannot parse json when Content-Type header contains more than just 'application/json'

### ISSUE THREAD

**Issue by samiruppaluru** [marshmallow-code/webargs#5]
In flaskparser.py:

``` python
def parse_json(self, req, name, arg):
        """Pull a json value from the request."""
        if req.content_type == 'application/json' and hasattr(req, 'json'):
            try:
                return core.get_value(req.json, name, arg.multiple)
            except AttributeError:
                return None
        else:
            return None
```

The 'Content-Type' header is checked to be exactly equal to 'application/json'. 

This prevents parsing of other valid 'Content-Type' headers, such as
`Content-Type:application/json;charset=UTF-8`
which is what my application sends with its AJAX requests.

Could we change the code to check that the Content-Type _**contains**_ instead of equals 'appliation/json' to handle these cases?

**Comment by sloria** [comment]
Thanks for reporting. You are correct that the header check is incorrect. However, I think the solution here is to use `request.get_json()`, as the [Flask docs suggest](http://flask.pocoo.org/docs/api/#flask.Request.json). I will hotfix this.

**Comment by samiruppaluru** [comment]
@sloria Thanks! Works great.
