### ISSUE TITLE
Validate list values with `multiple=True`

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/webargs#50]
For `Arg` objects with `multiple=True`, the validators are applied to each item in the list, but there doesn't seem to be a way to validate the overall list. Use cases: checking for duplicates, checking length of list is greater or less than some count.

Should webargs support this, or does this logic fit better elsewhere?

**Comment by sloria** [comment]
This is now addressed by virtue of using marshmallow's `List` field.
