### ISSUE TITLE
How to process many=True and many=False in same use_args? 

### ISSUE THREAD

**Issue by ColdHeat** [marshmallow-code/webargs#503]
Say I want to support the following JSON bodies in the same endpoint, how would I represent this in a call to `use_args`? 

```
{
  "name": "John"
  "age": 20,
  "hair_color": "brown",
}
```
and 
```
[
  {
        "name": "John"
        "age": 20,
        "hair_color": "brown"
  },
  {
        "name": "Sarah"
        "age": 21,
        "hair_color": "blonde"
  },
]
```

Is the correct approach to call `use_args` twice? 

For example:

```
@use_args(PersonSchema(many=True), location="json")
@use_args(PersonSchema(), location="json")
def post(bulk, obj):
    pass
```

**Comment by lafrech** [comment]
I'm afraid there is no native way to do this.

Out of my head (untested):

You could call `use_args` twice but I think it would fail as the many=True Schema would fail on single input and conversely. You might be able to solve this with a pre_load method that would empty the input if many = True and it is not a collection (and conversely). Sounds a bit twisted.

Unless there is a simpler way I'm not thinking of.

**Comment by ColdHeat** [comment]
I think this was able to work in my code with two calls to `use_args` and each set of args came as a separate argument. I don't really like that approach though so I'll look for an alternative.

**Comment by sirosen** [comment]
I've handled cases similar to this in the past with a "wrapper" schema which contains two fields, each pointing at a nested schema with different variations. Not complete code here, but a start might be this:

```python
class PersonSchemaWrapper(Schema):
    singular = fields.Nested(PersonSchema())
    multiple = fields.Nested(PersonSchema(many=True))

    @pre_load
    def dispatch_to_nested(self, obj, **kwargs):
        if isinstance(obj, list):
            return {"multiple": obj}
        return {"singular": obj}

    @post_load
    def unwrap(self, obj, **kwargs):
        if "singular" in obj:
            return obj["singular"]
        return obj["multiple"]
```

**Comment by sirosen** [comment]
I think this is answered? Or at least, I'm hoping my answer is good enough.
In any case, `marshmallow` itself can handle complex deserializations, so I don't think that anything we'd do for this -- if we added documentation -- belongs here.

I'm going to close, but I'm happy to discuss further if we want doc updates to show how to do this.
