### ISSUE TITLE
[RFC] Make it possible to pass data from multiple locations into a schema without custom locations

### ISSUE THREAD

**Issue by sirosen** [marshmallow-code/webargs#531]
### Problem Statement

I have a pattern in one of my applications which may (or may not) be common. Certain request bodies have validity checking and rules which actually depend on the path parameters which were used.

I'm wondering if there's some way we could support combining locations without defining custom locations.

Basically, I want to be able to have webargs/marshmallow handle checking that data from `path/query/json/...` locations are consistent with one another.

Full disclaimer: I only have _one_ case at my work in which I'd like this. I'm not sure if it's a general issue or a one-off.

#### Example App

To illustrate the issue, imagine a small API which supports `PUT /users/<user_id>` with a JSON body.

Naturally, we'll have some User schema to validate those JSON documents. Perhaps like this:

```python
class UserSchema(Schema):
    user_id = fields.Int()
    username = fields.String()
    # some list of IDs, it doesn't matter what
    admin_of_entities = fields.List(fields.Int)
```

Here's where it starts to get a little interesting. We'll stipulate that the API should allow you to send a `user_id`, but it must match the PATH. So we allow this:
```
PUT /users/101
{
  "user_id": 101,
  "username": "foo"
}
```
and disallow this:
```
PUT /users/102
{
  "user_id": 101,
  "username": "foo"
}
```

Webargs doesn't make it easy to do this as part of your parsing and validation because there's no way to pass the parsed path parameters to the call which parses JSON data.

Let's take it a step further. The API should only allow you to set `admin_of_entities` if the User has an underlying property `is_admin = True`.

So we should allow this call:
```
PUT /users/101
{
  "admin_of_entities": [101, 102]
}
```
only if the User with ID `101` is an admin.

Ideally, you'd like to do this in a `validates_schema` or `validates` hook on the `UserSchema`.
Something like
```python
@validates_schema
def meets_admin_constraints(self, data, **kwargs):
    user_object = lookup_user_by_path_param()  # mystery function, assume it exists
    if user_object.is_admin:
        return
    if "admin_of_entities" in data:
        raise ValidationError("You cannot specify 'admin_of_entities' on non-admin users.")
```

### Why it's important

If we ask users to push validation like this down into their view code, then it diminishes the utility of the error handler they attach to the webargs parser. In general, they'll want to transform marshmallow errors into some framework/application specific error. But if they can't push all of the validation into schema loading, then they have to have separate validation logic and potentially multiple error handlers.

It also means that if they have some common transforms they want to perform on request data -- things they'd like to do in `post_load` hooks -- they may have to push that logic into a custom decorator or down into views in an undesirable way.

### Workarounds Available Today

You can define a custom location which combines data from multiple locations.
Once that's done, you can pass the result to a combined schema of some kind.

However, this is not a particularly easy interface -- I'd say we basically don't support this kind of usage today but have a valid extension point for users to add support on their own.

If this is really rare, maybe it's not important to have a nicer solution than this?

### Sample Solution

This is not necessarily the right way to allow this, but what if webargs simply gave you a way to envelope together data from multiple locations? Then you can do whatever you want with a schema that handles the combination of data.

Imagine this interface:
```python
class UserIdSchema(Schema):
    user_id = fields.Int(required=True)

class UserSchema(Schema):
    user_id = fields.Int()
    username = fields.String()
    admin_of_entities = fields.List(fields.Int)

class CombinedSchema(Schema):
    # using Dict would be safer than Nested in this scenario because you're not
    # guaranteed that the "child" location schemas don't transform the data via post_load hooks
    path = fields.Dict(required=True)
    body = fields.Dict(required=True)

    @validates_schema
    def ids_match(self, data):
        if data["path"]["user_id"] != data["body"]["user_id"]:
            raise ValidationError("'user_id' in body did not match 'user_id' in path.")

    @validates_schema
    def meets_admin_constraints(self, data, **kwargs):
        user_object = lookup_user_by_id(data["path"]["user_id"])
        if user_object.is_admin:
            return
        if "admin_of_entities" in data["body"]:
            raise ValidationError("You cannot specify 'admin_of_entities' on non-admin users.")

    @post_load
    def unpack_body(self, data, **kwargs):
        return data["body"]

...

parsed_user = parser.parse(
    CombinedSchema,
    # making this a dict of objects of some kind for deferred parsing gives a good interface
    # it makes it possible to give a signature almost the same as `parse()`
    combines={
        "path": parser.dependency(UserIdSchema, location="path"),
        "body": parser.dependency(UserSchema, location="json"),
    }
)
```

This kind of approach would not require a tremendous overhaul. `parse()` would just need to check `combines` as an alternative to `location`, and, if a dict is given there, doing the nested `parse()` invocations on dependencies replaces the "load location data" step.

Do we like this? Is it a good idea, worth pursuing?

**Comment by lafrech** [comment]
With current webargs, I would do the validation in a the view func (or a nested decorator) and call webargs'`abort`  in case of validation error.

Calling abort, you get the same error handling as for marshmallow errors so there's not that much duplication.

Not saying your proposal is useless, just not sure it is worth the trouble.

**Comment by sirosen** [comment]
I'm going to self-close this. I think it would be _cool_ to do something like this, but _cool_ is not the same as necessary, useful, or easy to maintain.

In the time since I opened it, nobody showed up and 👍ed it, which is pretty much all the feedback I need.
