### ISSUE TITLE
Getting some weird import errors ModuleNotFoundError

### ISSUE THREAD

**Issue by cmabastar** [marshmallow-code/webargs#535]
Hello, 

I've been using webargs since 6.0 and wasn't really having this issue earlier until like 3 days ago. 

I'm using zappa which deploys to AWS lambda and getting this error at the moment.

> [ERROR] ModuleNotFoundError: No module named 'setuptools._distutils'Traceback (most recent call last):  File "/var/task/handler.py", line 656, in lambda_handler    return LambdaHandler.lambda_handler(event, context)  File "/var/task/handler.py", line 250, in lambda_handler    handler = cls()  File "/var/task/handler.py", line 147, in __init__    self.app_module = importlib.import_module(self.settings.APP_MODULE)  File "/var/lang/lib/python3.7/importlib/__init__.py", line 127, in import_module    return _bootstrap._gcd_import(name[level:], package, level)  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import  File "<frozen importlib._bootstrap>", line 983, in _find_and_load  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked  File "<frozen importlib._bootstrap_external>", line 728, in exec_module  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed  File "/tmp/glimpse-vision/autoapp.py", line 6, in <module>    from app.app import create_app  File "/tmp/glimpse-vision/app/app.py", line 10, in <module>    from webargs.flaskparser import abort, parser  File "/tmp/glimpse-vision/webargs/__init__.py", line 1, in <module>    from distutils.version import LooseVersion  File "/var/task/_distutils_hack/__init__.py", line 82, in create_module    return importlib.import_module('._distutils', 'setuptools')  File "/var/lang/lib/python3.7/importlib/__init__.py", line 127, in import_module    return _bootstrap._gcd_import(name[level:], package, level)  File "/tmp/glimpse-vision/setuptools/__init__.py", line 5, in <module>    import distutils.core  File "/var/task/_distutils_hack/__init__.py", line 82, in create_module    return importlib.import_module('._distutils', 'setuptools')  File "/var/lang/lib/python3.7/importlib/__init__.py", line 127, in import_module    return _bootstrap._gcd_import(name[level:], package, level) | [ERROR] ModuleNotFoundError: No module

**Comment by sirosen** [comment]
You're running in an environment where `distutils` is not available. `distutils` is part of the standard library, but I believe you can build python from source without it.

It appears at first, therefore, that this is not a `webargs` issue -- supporting interpreters missing key parts of the standard lib is not feasible for most libraries.
However, if you can find evidence that this is beyond your control (e.g. `zappa` is known to cause this issue by building a python environment without `distutils`) or a very prevalent problem, I'd be willing to look into workarounds.

**Comment by sirosen** [comment]
After giving this a few minutes of thought, I'm going to close this as not being a webargs issue to solve. I'm happy to reconsider if this is a broad issue and not just a one-off case of a broken python interpreter.
