### ISSUE TITLE
Drop support for marshmallow 2

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/webargs#539]
marshmallow 2 is EOL as of 2020-08-18

**Comment by sirosen** [comment]
Since we have a bunch of things queued up for 7.0, I'm going to create a 7.0-dev branch to work on this and other things.

cc @lafrech , just want to give you a heads up that I'm doing this.

**Comment by sirosen** [comment]
Now that I've pushed 7.0.0b1 , this is done in dev. I thought I had a `closes #XXX` commit in there, but I guess not.
