### ISSUE TITLE
Drop Python 3.5

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/webargs#543]
and update black.

See https://github.com/marshmallow-code/apispec/pull/582

**Comment by sirosen** [comment]
Ah, if we're dropping 3.5 then I think we can add more liberal type hints too! Exciting.
I'm happy to do this in the 7.0 branch when I get a chance.

Question: should I close out these 7.0 issues as work merges to that branch?

**Comment by lafrech** [comment]
Nice if you can do it. I could but have other priorities ATM. Especially if you intend to do some typing work as I'm not familiar with this.

Regarding branch 7.0, we could do the opposite: work on 7.0 in dev branch and keep a 6.x branch for v6 maintenance.
