### ISSUE TITLE
[RFC] Should missing JSON bodies raise errors by default?

### ISSUE THREAD

**Issue by sirosen** [marshmallow-code/webargs#546]
At work, we have an extra layer of validation to make sure a JSON body is present before `webargs` gets invoked. I'd like to be able to drop that and rely on webargs to guarantee me a JSON body.

This is something I'd like to
1. Make configurable
2. Possibly change the default for v7.0

Right now, if you use `parse(..., location="json")`, then certain non-json requests will pass `{}` to `Schema.load`. That's fine if you wanted the body to be optional, but it's not good behavior if you wanted to require a JSON payload.

I'm trying to think of a way to make this behave better for the "body required" case.
It can be done by subclassing the parser and overriding `load_json`, but I think webargs can do better by making the behavior toggleable.

There are two locations in the current code at-issue. `Parser._raw_load_json` may return `missing` based on the content-type, and `Parser.load_json` defaults to returning `missing` if there's a decoding error and the body was `""`.

Here's what I propose:
- add a setting to parsers, `Parser.optional_json: bool` which controls the behavior
- if `Parser.optional_json is True`, use the current behavior
- if `not Parser.optional_json`, raise a ValidationError in `_raw_load_json` on a bad content-type (which will result in  `_handle_invalid_json_error` being called)
- if `not Parser.optional_json` do not suppress json decoding errors on `body = ""` and instead invoke `_handle_invalid_json_error`
- _backwards incompatible_: set `Parser.optional_json = False` by default

This might require refactoring `json_or_form`.

@lafrech, I'm curious what you think of this?
It only needs to be in 7.0 if we want to change the default. So if you think it's interesting but not worth changing the default behavior, I'll remove it from the milestone.

**Comment by lafrech** [comment]
I had a quick look to https://swagger.io/specification/ and didn't see how to specify that a body is required.

I don't really see a use case for requiring a body. I mean, one can require a specific field in the body and webargs will 422 if that field is missing. But if no field is required, why require the body?

Or maybe I misunderstood the whole thing.

Regarding v6 vs. v7, I wouldn't bother and I'd put it in v7 either way. Hopefully, it shouldn't be too long to ship. I don't think it is worth doing it in both branches. But that's up to you, I don't mind.

**Comment by sirosen** [comment]
When I first started using it, I found it surprising that webargs translated an empty body into `{}`.
So I was looking for ways to improve things before cutting 7.0, and remembered this.
(Maybe I'm in the minority finding that behavior surprising though!)

I think it would be a nice way to improve the error message when no body is provided to be more appropriate.
Getting back `{"json": ["Invalid JSON body."]}` is clearer to the user than `{"json": {"foo": ["Missing data for required field."]}}`.
i.e. It's not about the case when no fields are required, but about the way that an error is produced when fields are required but no data is present.

This is not at all necessary, so if you're not convinced, I'll probably just drop it.
At work, we have a custom parser with an overridden `load_json` handler. Which is a pretty easy extension point to use for this.

And yeah, I'm hoping to get some time soon -- maybe this weekend -- to work on things for 7.0, like dropping py3.5 and adding some more annotations.

**Comment by sirosen** [comment]
I think we can dismiss this. I like giving a special message for a missing payload, but I don't need webargs to do it out of the box.

And it doesn't sound like anyone else is looking for this -- not sure if I should have expected any users to weigh in.
