### ISSUE TITLE
Remove/rename "remove" version

### ISSUE THREAD

**Issue by mekanix** [marshmallow-code/webargs#550]
In the [list of versions](https://github.com/marshmallow-code/webargs/releases?after=4.2.0) there is one called [remove](https://github.com/marshmallow-code/webargs/releases/tag/remove) which is triggering [FreeBSD notification system](https://portscout.freebsd.org/meka@tilda.center.html). It makes tracking of versions somewhat harder. Can you rename or remove that version (whatever you see fit), please? Thank you!

**Comment by lafrech** [comment]
I must have been done by mistake. Like trying to remove a tag with

    git tag remove ...

then pushing all tags.

I always push tags manually using

    git push origin tag_name

to avoid pushing garbage. But sometimes it slips through.

It does not appear on Pypi and considering the name, I doubt anyone actually relies on it, so I think it is safe to delete the tag.

Let me do this.

For the record, the commit is  ab33f80, it was replaced with beedfb6, tagged 2.1.0.

**Comment by lafrech** [comment]
Done. Thanks again @mekanix for the packaging work.

**Comment by mekanix** [comment]
You're most welcome. It's always nice watching you close tickets! :o)
