### ISSUE TITLE
Add more type annotations to base parser methods

### ISSUE THREAD

**Issue by sirosen** [marshmallow-code/webargs#566]
There are a number of type annotations on `AsyncParser` which I'd like to port over to the base `Parser` class as well.
I think `AsyncParser` got them first because it was able to assume a py3 runtime before the rest of the codebase could do so.

It's possible, especially with a large number of new annotations, that something will be subtly wrong or too restrictive. e.g. `location: str` instead of `location: Optional[str]` somewhere. If v7 introduces the new annotations, it might help to keep churn for users to a minimum.
Therefore, I'm marking this for 7.0 and will try to get to it very soon.

We could do this after v7 too, but it shouldn't be too hard to include this one last change.

**Comment by lafrech** [comment]
> I think AsyncParser got them first because it was able to assume a py3 runtime before the rest of the codebase could do so.

Exactly.

> It's possible, especially with a large number of new annotations, that something will be subtly wrong or too restrictive. e.g. location: str instead of location: Optional[str] somewhere. If v7 introduces the new annotations, it might help to keep churn for users to a minimum.

Sure.

> Therefore, I'm marking this for 7.0 and will try to get to it very soon.

Alright.
