### ISSUE TITLE
webargs 6.x -> 7.x - NoReturn issue in python 3.7.1

### ISSUE THREAD

**Issue by AbdealiLoKo** [marshmallow-code/webargs#573]
When I upgraded my webargs from `6.1.1` to `7.0.1`, I started getting this error:

```python
11:54:14 venv/lib/python3.7/site-packages/webargs/__init__.py:7: in <module>
11:54:14     from webargs.core import ValidationError
11:54:14 venv/lib/python3.7/site-packages/webargs/core.py:33: in <module>
11:54:14     ErrorHandler = typing.Callable[..., typing.NoReturn]
11:54:14 /opt/miniconda3/lib/python3.7/typing.py:755: in __getitem__
11:54:14     return self.__getitem_inner__(params)
11:54:14 /opt/miniconda3/lib/python3.7/typing.py:251: in inner
11:54:14     return func(*args, **kwds)
11:54:14 /opt/miniconda3/lib/python3.7/typing.py:774: in __getitem_inner__
11:54:14     result = _type_check(result, msg)
11:54:14 /opt/miniconda3/lib/python3.7/typing.py:135: in _type_check
11:54:14     raise TypeError(f"Plain {arg} is not valid as type argument")
11:54:14 E   TypeError: Plain typing.NoReturn is not valid as type argument
```

On searching around I found that this issue is most likely due to: https://bugs.python.org/issue34921
And I was using python 3.7.0 - which is affected.

Just thought I'd bring it up here, that webargs 7.x won't work with python 3.7.0 and 3.7.1

**Comment by lafrech** [comment]
I don't think there's anything we should do about this in webargs since the bug was in Python and was fixed, but thanks for sharing this, it may help someone facing the same issue.

**Comment by kasium** [comment]
@lafrech I just also hit this issue and switching to another python version is kind of hard (various reasons).
Therefore I would like to ask if you would be open to accept a simple PR which just adds a simple `if` to avoid this issue.

If you don't think that this makes sense, you might want to consider to update the `python_requires`

**Comment by sirosen** [comment]
> If you don't think that this makes sense, you might want to consider to update the `python_requires`

I think we'd welcome a patch to our `python_requires` to `>=3.7.2`.
This actually happened to us (also `NoReturn`, IIRC) in python 3.6.0 and we set `python_requires>=3.6.2` to fix it.

IMO `python_requires` is the only appropriate way to handle this. Conditional logic for type annotations can have some nasty implications.

**Comment by kasium** [comment]
@sirosen thanks, I'll create a PR
