### ISSUE TITLE
Keep track of decorated function names to assist with automatic API documentation

### ISSUE THREAD

**Issue by kirsle** [marshmallow-code/webargs#59]
This is a feature request for webargs that would make it easier to automatically generate API documentation in a web app. The specific use case in mind is for Flask, but this could probably help with other types of apps.

The only code change necessary in webargs is to keep track of the wrapped function names and associate it with the arguments attached to that function, and have a method to extract that mapping so it can be used by the app.

For example:

``` python
from flask import Flask
import webargs
from webargs.flaskparser import use_kwargs

app = Flask(__name__)

@app.route("/signup")
@use_kwargs({
    "name": Arg(str),
    "password": Arg(str),
    "accept_agreement": Arg(bool),
})
def signup(name, password, accept_agreement):
    pass

@app.route("/api_doc")
def make_api_doc():
    # we should be able to extract the route and arg mapping from webargs here
    webargs_map = webargs.arg_map()
```

The argument map would be a data structure that contains attributes like the following:

``` python
{
    "endpoint": "signup",  # the python function name wrapped by @use_kwargs
    "kwargs": {
        "name": Arg(str),
        "password": Arg(str),
        "accept_agreement": Arg(bool),
    }
}
```

Using this data, a Flask app can correlate it with `current_app.url_map` (where Flask keeps a mapping between URL routes and function names) to generate automatic API documentation. For example, an endpoint could generate HTML docs listing out the Flask URL routes (like `/signup`) and all of the parameters it accepts, including their names and types.

This can probably be implemented in `webargs.core.Parser` in the `use_args` decorator's implementation; keep a mapping between the wrapped `func.__name__` and its `argmap` and store it in a global variable and provide a method to get the current contents of that variable.

**Comment by sloria** [comment]
Thanks for the suggestion @kirsle . I like the idea. We will certainly consider this as we develop the webargs plugin for [smore](https://github.com/marshmallow-code/smore).

**Comment by sloria** [comment]
Holding off on this for now. Projects such as [flask-apispec](https://github.com/jmcarp/flask-apispec) show that argument data and metadata can be extracted without having to store them intenally in webargs.
