### ISSUE TITLE
support for webapp2 framework?

### ISSUE THREAD

**Issue by attwad** [marshmallow-code/webargs#6]
Hi, just wondering if you planned on supporting the webapp2 framework which is using standard webob requests objects. This would make this library usable on appengine with more frameworks and would be awesome.
Thanks!

**Comment by sloria** [comment]
I do not have plans to add support for a webapp2 parser in the near future.

That said, new parsers are relatively simple to create. You would only need to create a `Parser` class that implements the methods for parsing webob requests. See the existing parsers for examples.
