### ISSUE TITLE
Dates... ?

### ISSUE THREAD

**Issue by imhoffd** [marshmallow-code/webargs#60]
I'll preface this with what I would **like** to do:

``` python
args = {'start_date': Arg(datetime, convert=from_iso8601)}
parser.parse(args)
# {'start_date': datetime.datetime(2015, 9, 4, 22, 42, 31, 238157, tzinfo=<UTC>)}
```

So `from_iso8601` is a input conversion function supplied by webargs. It'd be cool to have `from_rfc3339` and `from_format` used like `partial(from_format, 'd/%m/%y %H:%M')` which uses [strptime](https://docs.python.org/3.4/library/datetime.html#strftime-strptime-behavior), and maybe `from_rfc822`.

I don't see this happening without extending `Arg` and overriding `_validate` because of [this line](https://github.com/sloria/webargs/blob/db76dd4f11b814f004d28bc8f1cfdcdb8790805b/webargs/core.py#L255), which assumes type conversion is as simple as "calling" the type, where, in reality, there may be several different methods to convert one type to another, such as a decimal to an integer, where [rounding alone yields six conversion methods](https://en.wikipedia.org/wiki/Rounding#Tie-breaking).

I will do a pull request, but I just wanted to know if there is something I am overlooking. I just started using webargs yesterday.

**Comment by jfpoilpret** [comment]
Actually, you can do it directly, without any need to specify type, and then you can provide your own conversion function.

Here is what I do in my app:

```
DEFAULT_DATE_FORMAT = '%d-%m-%Y'

def string_to_date(format = DEFAULT_DATE_FORMAT):
    def convert(input):
        return datetime.strptime(input, format) if input else None
    return convert

ALERT_DELETE_ARGS = {
    'clear_until': Arg(required = False, use = string_to_date()),
}
```

`string_to_date()` is a function returning a conversion function directly usable in `Arg` constructor. This way you can specify different formats for different arguments.

The important point here is to **not specify** type.

I'll let you find necessary adaptations for other RFC.

**Comment by imhoffd** [comment]
Ah, that's the feature I must have missed/overlooked. Thanks, I'll give this a try.
