### ISSUE TITLE
Will webargs support quart or other async framework?

### ISSUE THREAD

**Issue by aDisplayName** [marshmallow-code/webargs#608]
Is there any plan to support Quart?
https://gitlab.com/pgjones/quart

**Comment by aDisplayName** [comment]
I noticed the existence of webargs.AsyncParser, but could not find a way to make it work in quart. Is the feature ready? or some example somewhere?

**Comment by sirosen** [comment]
Third party parsers are documented in the wiki on [the ecosystem page](https://github.com/marshmallow-code/webargs/wiki/Ecosystem). (@lafrech, should we maybe make a link to this page for additional parsers more prominent in the readme? Looking at the readme, I don't think it's easy for people to find that page.)

There is a quart parser, [webargs-quart](https://github.com/esfoobar/webargs-quart) listed there. But it looks a little old and would need to be updated to work with the latest webargs versions.

`webargs.AsyncParser` is the basis for the [aiohttp parser](https://webargs.readthedocs.io/en/latest/api.html?highlight=aiohttp#webargs.aiohttpparser.AIOHTTPParser). [The source](https://github.com/marshmallow-code/webargs/blob/eaa349c2db4e09b62e650e8536c94067bfa5cf0d/src/webargs/aiohttpparser.py#L71) for that is pretty short and should make writing your own parser possible.

We've moved away from adding built-in parsers for various frameworks, so there's no plan to add a quart parser to `webargs` itself. But nor is there any plan to remove the existing parsers.

**Comment by aDisplayName** [comment]
@sirosen ,
Thank you. Actually I did copy the code from aiohttp parser and changed it a bit to work locally for my quart. If webargs-quart is indeed where it should be, I will go there submit a PR then...

**Comment by lafrech** [comment]
> @lafrech, should we maybe make a link to this page for additional parsers more prominent in the readme? Looking at the readme, I don't think it's easy for people to find that page.

Yes, absolutely.

Edit: BTW, I just updated the page to update flask-rest-api -> flask-smorest, long overdue, and add APIFlask.
