### ISSUE TITLE
Use marshmallow under the hood

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/webargs#61]
### Proposal

Replace `Arg` objects with marshmallow fields. Use marshmallow for validation.
### Why?

Webargs and marshmallow have redundant functionality for validating input data against a user-defined schema. Marshmallow does a better job of than webargs in a number of respects:
- Nested validation is much more powerful in marshmallow. marshmallow's `Nested` field would solve #39 and #51.
- Marshmallow does error bundling. Solves #58 
- Marshmallow handles null and missing inputs in a more predictable way.
- Marshmallow has more consistent error messaging.
- Marshmallow's validation is more stable and well-tested
### Proposed API

``` python
from webargs import use_kwargs, fields


@use_kwargs({
    'title': fields.Str(required=True, location='json'),
    'description': fields.Str(required=False),
})
def myview(title, description):
    return 'title: {}, description: {}'.format(title, description)


# with nesting
@use_kwargs({
    'data': fields.Nested({
        'title': fields.Str(),
        'description': fields.Str(),
    })
})
def myview(data):
    return 'title: {}, description: {}'.format(**data)


# respects load_from
@use_kwargs({
    'x_custom_header': fields.Str(load_from='X-Custom-Header')
})
def myview(x_custom_header):
    return 'Header: {}'.format(x_custom_header)


# Passing in a Schema
from marshmallow import Schema

class PostSchema(Schema):
    title = fields.Str(required=True, location='json')
    description = fields.Str(required=False)
    id = fields.Int(dump_only=True)  # won't be included in parsed output

@use_kwargs(PostSchema)
def myview(title, description):
    return 'title: {}, description: {}'.format(title, description)
```

**Comment by marcellarius** [comment]
This seems like a good solution to me.

**Comment by hello-josh** [comment]
+1

**Comment by sloria** [comment]
Making lots of progress on this.

I haven't yet decided where fields should be imported from.

Here are the alternatives (note that `Nested` is a webargs-specific field):

(1) Import from `webargs.fields`

``` python
from webargs import fields
from webargs.flaskparser import use_args
from marshmallow import validate

@use_args({
    'data': fields.Nested({
        'id': fields.Int(),
        'email': fields.Str(validate=validate.Email()),
    })
})
```

(2) Import from `webargs`

``` python

import webargs as wa
from webargs.flaskparser import use_args
from marshmallow import validate

@use_args({
    'data': wa.Nested({
        'id': wa.Int(),
        'email': wa.Str(validate=validate.Email()),
    })
})
```

(3) Import from `marshmallow`

``` python
from webargs import Nested  # or from webargs.fields import Nested
from webargs.flaskparser import use_args
from marshmallow import fields, validate

@use_args({
    'data': Nested({
        'id': fields.Int(),
        'email': fields.Str(validate=validate.Email()),
    })
})
```

Any preferences?

**Comment by marcellarius** [comment]
1) or 3).  I think option 3) makes it clear that it's using marshmallow.

**Comment by sloria** [comment]
Fair point. On the other hand, perhaps we don't want to "leak" the marshmallow abstraction? As a user, I don't really like being required to import a 3rd-party library's (marshmallow) modules in the common case, but that's personal preference.

**Comment by sloria** [comment]
From discussion with @jmcarp : "I think i prefer 1 or 2 just so it's harder to use the wrong `Nested`".

**Comment by hello-josh** [comment]
I would argue that you shouldn't import from Marshmallow at all. If you want to use Marshmallow under the good, go all the way. 

`from webargs import fields, validate`

**Comment by sloria** [comment]
To play devil's advocate: there's a risk of hiding _too much_. If users import `Schema` from webargs, they might think that webargs modifies behavior of vanilla marshmallow Schemas in some way.

That said, I think importing `fields` and `validate` from webargs is fine.

**Comment by sloria** [comment]
There's also an argument for future-proofing: we can always add imports to webargs without breaking backwards-compat; we cannot remove them without breaking compat.

**Comment by sloria** [comment]
The `marshmallow` branch is merged. We'll have a release out later today.

**Comment by hello-josh** [comment]
:+1:
