### ISSUE TITLE
Consider switching sphinx theme

### ISSUE THREAD

**Issue by sirosen** [marshmallow-code/webargs#610]
I see that https://github.com/marshmallow-code/webargs/pull/607 is failing with an error because `sphinx-typlog-theme` is somehow mismatching with `sphinx==4.0.2`. I haven't looked carefully into what that error about `metatags` means, but I'm betting it was dropped in sphinx v4 and sphinx is now catching this usage.

Given that the theme hasn't been updated in a couple of years, I wonder if we should consider switching the theme for webargs?

We could go with alabaster, which is what marshmallow uses, or the new hotness of [furo](https://github.com/pradyunsg/furo).
I've been looking at `furo` for some things at work, and I like generally how it looks and feels.

@sloria, @lafrech, what do you guys think? Try out `furo`, switch to `alabaster`, or should we look at contributing a fix to the typlog theme?

**Comment by lafrech** [comment]
+1 for switching vs. trying to fix. I always wondered why webargs had a different theme.

I'd go for consistency with marshmallow. But I don't mind at all, so you're free to use furo if you like it.

I just realized apispec also has a different theme than marshmallow.

**Comment by sloria** [comment]
> I always wondered why webargs had a different theme.

there was a point in history where webargs was completely separate from marshmallow. the docs may have been created before it became a marshmallow-code project. also, i liked the organization of the typlog theme; i found it easier to navigate than alabaster.

no strong opinion, but switching to furo seems like a good choice.

**Comment by sirosen** [comment]
> also, i liked the organization of the typlog theme; i found it easier to navigate than alabaster.

I like the typlog theme pretty well too, but I think moving on to a new theme is logical at this point.
If you're not satisfied with alabaster, maybe it's worth considering `furo` for `marshmallow` docs too?

I'll open a PR to try out `furo` here and we can see the result.

**Comment by sirosen** [comment]
Well, this is slightly embarrassing for me!
[Furo doesn't support sphinx v4 yet.](https://github.com/pradyunsg/furo/blob/3483e736a9d3668a8d82c78bc128d73691400952/pyproject.toml#L14)

~I'll open an issue there to see if it's easy to handle, but I won't do a branch of `webargs` for it yet.~
EDIT: Turns out, there's [active effort on this](https://github.com/pradyunsg/furo/discussions/148) but in a discussion, so I didn't find it in an issue search. I'll just wait a little.

**Comment by sirosen** [comment]
closed by #615
