### ISSUE TITLE
422 Unprocessable Entity Http Code Raised

### ISSUE THREAD

**Issue by SLey3** [marshmallow-code/webargs#635]
I used the custom parser provided in: [Advanced Usage:Custom Parser](https://webargs.readthedocs.io/en/latest/advanced.html#custom-parsers)
I made small modifications entering my own custom dictionary so I could do the following:
```python
temp_save = _temp_save()
temp_save["banana"] = "oranges"
value = temp_save["apples"] or temp_save["banana"]
print(value) # oranges
```
I also added an error handler for the http 422 status code which showed the following error:

```
{
  "errors": {
    "query": {
      "actions": {
        "_schema": [
          "Invalid input type."
        ]
      }, 
      "page": [
        "Not a valid integer."
      ]
    }
  }
}
```
i don't know what the message under "_schema" means or where it could possibly be located but what I find interesting is that for the page paremeter it is stating that the integer that is set by default isn't a valid int. I checked and sure enough it is a valid integer as provided by the following parameter args:
```python
_account_user_manegement_webargs = {
    "user": fields.Str(required=True),
    "page": fields.Int(missing=1),
    "actions": fields.Nested({
        "action": fields.Str(missing=None),
        "item_id": fields.Str(missing=None),
        "page": fields.Int(missing=1)
    })
}
```
This is confusing to me as I don't know where exactly is the error message is referring to as I am using an actual integer for the page parameter and I think it may have to do something with the parser but I am not sure.

Parser source:
```python
class WebArgsNestedParser(FlaskParser):
    """
    Parses nested query args

    This parser handles nested query args. It expects nested levels
    delimited by a period and then deserializes the query args into a
    nested dict.

    For example, the URL query params `?name.first=John&name.last=Boone`
    will yield the following dict:

        {
            'name': {
                'first': 'John',
                'last': 'Boone',
            }
        }
    """
    def load_querystring(self, req, schema):
        return _structureddict(req.args)
    
def _structureddict(dict_):
    # modified to use ProjectsWebsite.utils._utils.temp_save dictionary
    def _pair(r: temp_save, key: K, value: V):
        m = re.match(r"(\w+)\.", key)
        if m:
            if r.get_without_pop(m.group(1)) is None:
                r[m.group(1)] = temp_save()
            _pair(r.get_without_pop(m.group(1)), m.group(2), value)
        else:
            r[key] = value
    r = temp_save()
    for k, v in dict_.items():
        _pair(r, k, v)
    return r
```
temp_save functions used in the parser:
```python
    def __getitem__(self, k: K, with_pop=True) -> Union[bool, None]:
        try:
            if with_pop:
                return self.pop(k)
            return super().__getitem__(k)
        except KeyError:
            return False
        
    def get_without_pop(self, k: K) -> Union[bool, None]:
        """
        gets item without the default behavior of popping the item
        """
        val = self.__getitem__(k, False)
        if not val:
            return None
        return val
```

**Comment by sirosen** [comment]
I should note that the custom parser is provided as an example to demonstrate how to subclass `Parser` and customize location loading. It's not really code we support (it's not in `webargs` for a reason).

As far as I know, passing a dict to `fields.Nested` is not a supported usage in `marshmallow`. You may want to just wrap that in [`Schema.from_dict`](https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.Schema.from_dict), which is what webargs does when it's passed a dict.

Not knowing what your input is, I can't really guess at what's causing your errors, but...
- `_schema` is used as a namespace for validation errors that happen at the schema-level.
- If `__getitem__` removes elements, I'm not sure that's valid. You might _technically_ satisfy `Mapping`, but I'm not even sure. That will almost certainly break lots of things.
- Consider writing your schema as a schema class -- or manually instantiating it with `from_dict` -- and testing it on various dicts before passing it to webargs. This will let you isolate testing of your schema from testing of your parser.

This is not really a `webargs` issue -- there's no bug or documentation defect -- so I'm closing it. You may want to ask StackOverflow about things like subclassing `dict` or `collections.UserDict`.
