### ISSUE TITLE
Replacing `Arg(dict)` with marshmallow?

### ISSUE THREAD

**Issue by jacebrowning** [marshmallow-code/webargs#65]
In `webargs < 0.16`, I have arguments defined as `Arg(dict, ...)`. How do I convert these to marshmallow fields? The [changelog](https://github.com/sloria/webargs/blob/dev/CHANGELOG.rst#0160-2015-09-27) shows examples with strings and nested arguments, but I couldn't find an example with `dict`.

**Comment by sloria** [comment]
You can use a custom `Dict` field:

``` python
import collections

class Dict(Field):
    default_error_messages = {
        'invalid': 'Not a valid dict.'
    }

    def _deserialize(self, value, attr, data):
        if isinstance(value, collections.Mapping):
            return value
        else:
            self.fail('invalid')
```

A `Dict` field will be added to marshmallow in https://github.com/marshmallow-code/marshmallow/pull/286 . Until that is released, the code above should meet your use case.

**Comment by sloria** [comment]
`Dict` field is in marshmallow 2.1.0, which is on the PyPI.

**Comment by yyyyyyuanfei** [comment]
I am trying to pass in a complex criterion dict in the querystring as shown below:

`/companies?where={'revenue': {'$in': ['$100-$200']}}`

The controller definition:

```
@use_args({
  'where': fields.Dict()
})
def get_companies(args):
   args['where']
   return '', httplib.OK
```

It seems the `where` arg is not parsed as a dict, but an unicode, when `marshamallow` tests it again the `collections.Mapping` it failed.

Am I missing anything to make it as a dict in the preprocess?

Thanks!!

**Comment by sloria** [comment]
@stranbird That is the expected behavior; `fields.Dict` does not expect to receive strings as input, and webargs does not do any special preprocessing. One solution is to create a custom field:

``` python
class JSONDict(fields.Dict):

    def _deserialize(self, value):
        if isinstance(value, str):
            value = json.loads(value)
        super()._deserialize(value)

@use_args({
  'where': JSONDict()
})
```

**Comment by yyyyyyuanfei** [comment]
@sloria neat solution, ty!
