### ISSUE TITLE
When will webargs drop support for python3.6?

### ISSUE THREAD

**Issue by sirosen** [marshmallow-code/webargs#665]
python3.6 reaches EOL in a couple of weeks. Should we keep it beyond the EOL date, or drop it immediately?

My one reason that we might continue support for a time: Ubuntu 18.04 runs py3.6 by default, and support doesn't end until 2023.

I think we can ignore CentOS/RHEL 7 (EPEL 7 provides python3.6). Regular maintenance has ended and they can get a newer python from SCL.

**Comment by lafrech** [comment]
Should we transfer this to marshmallow? There's no point keeping compat here if it is dropped in marshmallow.

I'd say drop it. Even Debian old stable has 3.7. People really willing to stick to Ubuntu 18.04 can always keep current webargs version. They should only need security fixes and we almost never issue security fixes anyway.

Perhaps we could make the "we drop EOL Python versions even in minor versions" rule more obvious in marshmallow docs (note we never got any complaint).

**Comment by sirosen** [comment]
> Should we transfer this to marshmallow? There's no point keeping compat here if it is dropped in marshmallow.

It makes more sense there, but maybe just close this. I agree that there's no point in staying compatible here if marshmallow drops 3.6.

I hadn't seen anything about this, but I now see you have a PR ready on marshmallow to drop 3.6.

> Perhaps we could make the "we drop EOL Python versions even in minor versions" rule more obvious in marshmallow docs (note we never got any complaint).

I think it matters more to me than to the average user. No need to update docs.

I'm fine with doing this in v8.1.0. I thought we were going to do v9.0.0 for it, so it seemed to me like a bigger deal which we'd want to discuss.

**Comment by lafrech** [comment]
Good. We'll do that, then!
