### ISSUE TITLE
The type of "argmap" allows for `Mapping[str, Field]`, but `Schema.from_dict` only supports `Dict[str, Field]`

### ISSUE THREAD

**Issue by sirosen** [marshmallow-code/webargs#679]
I ran into this while looking at getting #663 merged.

We have arguments annotated as allowing a `Mapping`. The most likely usage for users is just a dict, and that is all that our examples show.
`Schema.from_dict` uses `dict.copy`. That's not part of the `Mapping` protocol in `collections.abc`.

I almost suggested that `Schema.from_dict` be modified to allow for a `Mapping` object. It's not particularly hard (switch `input_object.copy()` to `dict(input_object)`), but it seems wrong. There's no particular reason to support non-dict mappings for either `marshmallow` or `webargs`. I think our annotations in `webargs` are just inaccurate.

I think we should consider updating annotations in `webargs` from `Mapping` to `Dict`.

@lafrech, for now, I'm going to make an update to the #663 branch and add `dict(argmap)` calls to make the types align.

**Comment by lafrech** [comment]
> I think we should consider updating annotations in webargs from Mapping to Dict.

Sure. This would be a fix since the code always expected a dict.
