### ISSUE TITLE
Doesn't respect defaults

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/webargs#68]
As of 0.16, webargs doesn't respect default values for missing fields:

``` python
@use_kwargs({'foo': fields.Str(default='bar')}
def view(foo):
    ...
```

If `foo` isn't found in the request, it should default to "bar", but it actually defaults to `marshmallow.missing`. It looks like we used to check for `missing` in `Parser.parse_arg` and return the default value if available, so we could restore that behavior to fix. Does that seem like the right approach @sloria? I can give this a try, or use another approach. Or you can fix it for me :guitar: 

Tested with Flask.

**Comment by sloria** [comment]
Try using the `missing` argument instead of `default`. `missing` defines the deserialization value when the input is missing.

**Comment by jmcarp** [comment]
Meh. Can I not pass `missing` as `None`? Seems to raise an error.

**Comment by sloria** [comment]
Yeah, the less-than-ideal naming comes from the fact that marshmallow fields can have different default values for deserialization vs. serialization.

The `missing` value still gets validated, so you will need to set `allow_none=True`. Perhaps this is a usability bug in marshmallow; it might make sense to set `allow_none=True` implicitly if `missing=None`.

**Comment by jmcarp** [comment]
:+1: to (considering) that API change on marshmallow. Thanks @sloria!

**Comment by sloria** [comment]
The above change is made in marshmallow 2.1.0.

**Comment by jmcarp** [comment]
Like!
