### ISSUE TITLE
Behavior of "allow_missing=True" with "multiple=True"

### ISSUE THREAD

**Issue by dgilland** [marshmallow-code/webargs#7]
Currently, when you define an `Arg` such as:

``` python
myargs = {'somearg': Arg(allow_missing=True, multiple=True)}
```

When `somearg` is not supplied, the parsed `myargs` is `{'somearg': []}`.

However, when you define an `Arg` with `multiple=False`:

``` python
myargs = {'somearg': Arg(allow_missing=True)}
```

When `somearg` is not supplied, the parsed `myargs` is `{}`.

I was surprised by this behavior as I assumed that when `allow_missing=True` and the argument is not supplied, that no parsed value would be returned for both the `multiple=False` and `multiple=True` cases.

Is this intentional? Or should no parsed value be returned in the case of `Arg(allow_missing=True, multiple=True)` instead of `[]`?

**Comment by sloria** [comment]
@dgilland You are correct; the current behavior is incorrect. In your example, `'somearg'` should not be in the parsed arguments if it is not passed.

I will issue a fix soon. Thanks for reporting!

**Comment by dgilland** [comment]
Awesome! Thanks for fixing the issue so quickly! :+1: 

Kudos on the library as well! Very helpful/useful.
