### ISSUE TITLE
Allow empty collections

### ISSUE THREAD

**Issue by mTatcher** [marshmallow-code/webargs#70]
When a fields.List is being parsed, it returns 'missing' if list is empty. Why not return empty list instead?

**Comment by mTatcher** [comment]
In core.py, parse_arg:

``` Python
if (is_multiple(field) and not
    (isinstance(value, collections.Iterable) and len(value))):
```

len(value) is checking if value is an empty list.
I suggest removing this check

**Comment by sloria** [comment]
@mTatcher Yes, I think and empty list should be returned if an empty list is passed from the client. That incorrect check appears to be a remnant from webargs' pre-marshmallow days.

Pull requests welcome!
