### ISSUE TITLE
Tags cleanup

### ISSUE THREAD

**Issue by mekanix** [marshmallow-code/webargs#716]
I would like to propose removal of [tag named "remove"](https://github.com/marshmallow-code/webargs/releases/tag/remove) or that it's  renamed to match other release format. As package maintainer on FreeBSD I get false notifications that "remove" is higher version of package and I should update. Example is [list of packages I maintain](https://portscout.freebsd.org/meka@tilda.center.html). It would mean a lot to me and probably other maintainers on other OS/distributions if notifications would work. Thank you!

**Comment by lafrech** [comment]
@sloria this tag looks like a mistake, right? May we remove?

I'll remove in a few days if I get no answer as I'm pretty sure this is meaningless. @mekanix please ping here if I forget.

(Unlike what is advertised in https://github.com/marshmallow-code/marshmallow/blob/dev/RELEASING.md, I always push each new tag explicitly to avoid sending local tags inadvertently.)

**Comment by sloria** [comment]
Ah yes, this was a mistake. good catch. i've removed it
