### ISSUE TITLE
v0.5.1 not installable via pip

### ISSUE THREAD

**Issue by dgilland** [marshmallow-code/webargs#8]
I tried to upgrade to 0.5.1, but pip says that 0.5.0 is the latest even though pypi shows this: https://pypi.python.org/pypi/webargs/0.5.1:

```
(env)[~/Desktop/test_webargs] $ pip --version
pip 1.5.6
(env)[~/Desktop/test_webargs] $ pip search webargs
webargs                   - A utility library for parsing HTTP request arguments, with built-in support for popular
                            web frameworks, including Flask and Django.
(env)[~/Desktop/test_webargs] $ pip install webargs
Downloading/unpacking webargs
  Downloading webargs-0.5.0-py2.py3-none-any.whl
Installing collected packages: webargs
Successfully installed webargs
Cleaning up...
(env)[~/Desktop/test_webargs] $ pip search webargs
webargs                   - A utility library for parsing HTTP request arguments, with built-in support for popular
                            web frameworks, including Flask and Django.
  INSTALLED: 0.5.0
  LATEST:    0.5.1
```

However, 0.5.1 is missing from https://pypi.python.org/simple/webargs/ which is where (I believe) pip is checking:

![screenshot from 2014-08-31 11 16 16](https://cloud.githubusercontent.com/assets/1251349/4102269/e0bc9850-3121-11e4-8846-d3324c1e7fb1.png)

**Comment by sloria** [comment]
Hm, it looks like there was a problem uploading the distribution using setuptools on Python 3. I was able to successfully re-upload in a Python 2 environment. You should now be able to upgrade to 0.5.1. 

Thanks for reporting this!
