### ISSUE TITLE
url parameters

### ISSUE THREAD

**Issue by oreza** [marshmallow-code/webargs#82]
Hi,
I am new to Flask and I am very very new to webargs, I was wondering why you guys decided to treat segment parameters differently than other parameters (form, query, heads),  view_args is part of request object and why not provide a view as location collection to parse the view_args and than before passing it back to the end point you can make sure it doest not exist kwargs. 

Cheers

**Comment by sloria** [comment]
Are you referring to something like this?

``` python
@app.route('/<name>')
@use_args({'name': fields.Str(location='view_args')})
def hello(args, name):
    return 'Hello {}'.format(args['name'])
```

I suppose this might be OK. After all, aiohttpparser and pyramidparser have the `match_info` and `matchdict` locations.

My concern is how `use_kwargs` would interact with `app.route`, since the two will inject the same keyword arguments.

**Comment by oreza** [comment]
Yes exactly, 

I have not tested kwargs but wouldn't you be able to remove duplicate from kwargs before passing it the function (return func(_new_args, *_kwargs))? 

If you want I can open a pull request, and you can look at it.

My personal reason for this is that  I have existing API, that has lots of EP with URL segment parameters and I want to use your library but I want to keep unified way to parse and validate arguments.

Cheers,

**Comment by sloria** [comment]
I would gladly review a PR for this. Thanks in advance!
