### ISSUE TITLE
Dealing with empty values in `DelimitedFieldMixin`

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/webargs#823]
`DelimitedList(String())` deserializes "a,,c" as `["a", "", "c"]`.

I guess this meets user expectations.

My expectation with integers would be that

`DelimitedList(Integer(allow_none=True))` deserializes `"1,,3"` as `[1,None,3]`

but it errors.

The reason for this is that when the string is split, it is turned into `["1", "", "3"]`. This is why it works in the string case.

I'm not sure this was really intended. It may be a side effect of the `split` function that happens to do well with strings.

We could change that to replace empty values with `None`. But it would break the string use case, unless the user overloads `String` field to deserialize `None` as `""`.

Likewise, users may already overload `Integer` to deserialize `""` as `None` and no modification is required to `DelimitedFieldMixin`.

Just been caught by this and wondering out loud. Advice welcome.

In any case, there is an intrinsic limitation in the delimited string format: one can't distinguish empty string from missing value (as opposed to a JSON payload). It is not clear to me how OpenAPI (for instance) deals with the case of an empty element in an array (in a query argument).

**Comment by sirosen** [comment]
We could add another argument/instance variable just for the empty case. I don't know if I like it yet as an idea, but we'd get...

```python
DelimitedList(String(), empty="")  # default
DelimitedList(Integer(), empty=0)
DelimitedList(Integer(allow_none=True), empty=None)
```

For the record, I think allowing for None has utility. I've seen APIs do things like
```
range=0,100
range=1,  # no upper bound
```

Having written that, I'm starting to think that I like adding an argument for this. It's not much new API surface and it ought to work. Are there other ideas we should consider (e.g. a classvar)?

**Comment by lafrech** [comment]
Indeed, adding an argument here makes total sense. Thanks.

Argument should be enough IMHO. Class var would allow someone to subclass to avoid the argument duplication but I don't think it is worth it.

I don't need this right now. But it is nice to keep this in the backlog so that anyone needing it can work on it. It is a pretty easy contribution.

It would be interesting to wonder how this can be documented in OpenAPI via apispec.
