### ISSUE TITLE
webargs.core.Parser should describe default for unknown either as marshmallow.EXCLUDE or "exclude"

### ISSUE THREAD

**Issue by gh-andre** [marshmallow-code/webargs#826]
Current description says this:

> unknown (str) – A value to pass for unknown when calling the schema’s load method. Defaults to EXCLUDE for non-body locations and RAISE for request bodies. Pass None to use the schema’s setting instead.

`EXCLUDE` doesn't exist as a symbol in webargs, only in marshmallow and trying something like `"EXCLUDE"` fails and it takes time to figure this one out. Perhaps this description should reference either `marshmallow.EXCLUDE` or a marshmallow's value, such as `"exclude"`, to make it more clear.

**Comment by sirosen** [comment]
This sounds to me like a reasonable documentation fix.

Let's go with `marshmallow.EXCLUDE` -- the fact that the constant is just a string is a detail of marshmallow, not something which is a clear and explicit part of marshmallow's API.
