### ISSUE TITLE
Raise a validation error if multiple query parameters are specified for non-List fields

### ISSUE THREAD

**Issue by immerrr** [marshmallow-code/webargs#84]
As of now, at least `flaskparser`, not sure about the others, fetches anything other than the first query parameter only if the field is a `List`. I think an error should be raised if multiple query parameters or headers are passed and only one value is expected by the schema, at least by default.

**Comment by sloria** [comment]
I'm not sure about this. I understand why you would want an error to be returned. On the other hand, ["Generous on input, strict on output"](http://tedwise.com/2009/05/27/generous-on-input-strict-on-output/) could be considered a valid rule of thumb.

I welcome other users' feedback on this.

For the time being, one workaround would be to override querystring parsing.

``` python
from webargs import core
from webargs.flaskparser import FlaskParser

class Parser(FlaskParser):
    def parse_querystring(self, request, name, field):
        if len(request.args.getlist(name)) > 1 and not core.is_multiple(field):
            raise core.ValidationError(
                'Multiple values provided for "{}". Expected one value.'.format(name),
                field_names=[name],
                fields=[field]
            )
        return super().parse_querystring(request, name, field)
```

**Comment by immerrr** [comment]
The problem with accepting multiple values where only one is expected is that there's an ambiguity about which option should work, e.g if user does `?delete=true&...&delete=false` I would really refuse the temptation to guess or rely on the fact that normal parsers would reliably return the first value all the time. For all we know, the user might just be writing a long query manually and forget to remove one copy-pasted query parameter.

DTRT principle resonates with me, so using "sane defaults" and allowing "1, 0, T, F, Y, N, TRUE, FALSE, YES, NO, etc." feels fine. It kind of makes sense to accept `?delete=true&...&delete=1` when you expect only one value, because there's no ambiguity. However I'd expect such situations to be quite rare and probably not worth the complexity of deserializing multiple values and ensuring that all inputs are equivalent.

**Comment by sloria** [comment]
Fair points. I do not feel strongly in favor of allowing multiple values for singular fields, so I would likely accept a PR implementing this change.

On a related note, I'm not sure whether to consider this a breaking change or not...

**Comment by sloria** [comment]
Closing this for now. Feel free to reopen if there is still interest in changing this.
