### ISSUE TITLE
Unused `status_code` field in `ValidationError`?

### ISSUE THREAD

**Issue by ParthGandhi** [marshmallow-code/webargs#85]
I'm trying to figure out how to return specific status codes from validation errors. Looks like it always returns a `422`, ignoring whats specified in the `ValidationError`.

``` python
from flask import Flask
from webargs import fields, ValidationError
from webargs.flaskparser import use_args

app = Flask(__name__)

def dummy_validator(val):
    raise ValidationError(message="Error!", status_code=500)

@app.route('/')
@use_args({'test_field': fields.String(validate=dummy_validator)})
def hello_world(args):
    return 'Hello World!'

if __name__ == '__main__':
    app.run('0.0.0.0', debug=True)
```

Then: `curl -v http://localhost:5000?test_field=hello` returns `422 Unprocessable Entity` instead of `500 Internal Server Error`.

**Comment by sloria** [comment]
This is a known bug. Since marshmallow catches `ValidationErrors`, collects and formats them, then reraises _a new_ `ValidationError`, there is currently no way to use the `status_code` attribute in a webargs Parser's `error_callback`.

I welcome any help and ideas on how to address this.

**Comment by lafrech** [comment]
@ParthGandhi any thoughts on https://github.com/marshmallow-code/marshmallow/issues/996?
