### ISSUE TITLE
Debian packaging for Python 2

### ISSUE THREAD

**Issue by freddrake** [marshmallow-code/webargs#86]
When building .deb packages using stdeb, the `webargs.aiohttpparser` and `webargs.async` modules are included, but cause errors during installation due to Python 3 syntax:

```
Unpacking python-webargs (1.2.0-1) over (1.2.0-1) ...
Setting up python-webargs (1.2.0-1) ...
  File "/usr/lib/python2.7/dist-packages/webargs/aiohttpparser.py", line 61
    yield from req.post()
             ^
SyntaxError: invalid syntax

  File "/usr/lib/python2.7/dist-packages/webargs/async.py", line 23
    parsed_value = yield from self.parse_arg(argname, field_obj, req,
                            ^
SyntaxError: invalid syntax

dpkg: error processing package python-webargs (--install):
 subprocess installed post-installation script returned error exit status 101
```

I used this command to generate the .deb package:

> python2.7 setup.py --command-packages=stdeb.command bdist_deb

and this command to install the generated .deb on an Ubuntu 14.04.3 system:

> sudo dpkg -i deb_dist/python-webargs_1.2.0-1_all.deb

This can be avoided by removing the files from the distribution when using Python 2.  I'm not sure what the best way to accomplish this is with the Debian tooling; using `exclude` statements in the MANIFEST.in file didn't do the trick.

**Comment by sloria** [comment]
Closing this. Further discussion should happen on #105.
