### ISSUE TITLE
Using location="view_args" results in duplicate arguments

### ISSUE THREAD

**Issue by tonycpsu** [marshmallow-code/webargs#89]
I'm trying to use the view_args functionality as implemented in #82.  Here's my test code:

``` python
import logging
import sys
from flask import Flask, Blueprint
from webargs import fields
from webargs.flaskparser import use_args

app = Flask(__name__)
blueprint = Blueprint("api", "api")

@blueprint.route("/resource/<foo>/<bar>")
@use_args({
    "foo": fields.Integer(location='view_args', required=True),
    "bar": fields.Date(location='view_args', required=True)
})

# def get(*args, **kwargs):
#     return repr(dict(args=args, kwargs=kwargs))
def get(foo, bar, *args, **kwargs):
    return repr(dict(foo=foo, bar=bar, args=args, kwargs=kwargs))


console_handler = logging.StreamHandler(sys.stderr)
console_handler.setLevel(logging.DEBUG)
app.logger.addHandler(console_handler)
app.register_blueprint(blueprint, url_prefix="/api")
app.run()
```

The first `get` method (commented out) works, but the values are in `args` and I'd rather have them passed as function parameters.  So I tried the second `get` method with `foo` and `bar` as function parameters, but get the following error:

```
Exception on /api/resource/1/2015-02-02 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/webargs/core.py", line 412, in wrapper
    return func(*new_args, **kwargs)
TypeError: get() got multiple values for keyword argument 'foo'
```

Am I using this functionality wrong?  My expectation is that it would pass the values of foo and bar as function parameters, replacing the ones parsed from the route definition.

**Comment by sloria** [comment]
`use_args` injects a dictionary of parsed arguments before any of the path URL kwargs, so your view should look like:

``` python
@blueprint.route("/resource/<foo>/<bar>")
@use_args({
    "foo": fields.Integer(location='view_args', required=True),
    "bar": fields.Date(location='view_args', required=True)
})
def get(reqargs, foo, bar, *args, **kwargs):
    return repr(dict(foo=reqargs['foo'], bar=reqargs['bar'], args=args, kwargs=kwargs))
```

**Comment by tonycpsu** [comment]
Cool, that works. Thanks!

**Comment by lkurija2** [comment]
Hey @sloria, why doesn't this work anymore? It seems like the `required=True` flag breaks the behavior, but even without it, the view args don't get validated.

**Comment by sirosen** [comment]
Please open a fresh issue describing what you're seeing, including what version of `webargs` you're using. This is over 7 years old and refers to a much earlier version of `webargs`.

**Comment by lkurija2** [comment]
It's the exact same issue, it's just that the fix you proposed no longer works. The error message is different though, because it doesn't surface, but the core error is the same if you debug it.

**Comment by sirosen** [comment]
`webargs` has gone through several major versions in the better part of the decade.

My request that you submit a new ticket is not a purely technical matter. It's also a social one. This thread is not the appropriate place to be discussing your issue. It's almost certainly not the same issue, even if it is related.
