### ISSUE TITLE
Feature request: Arg(allow_none)

### ISSUE THREAD

**Issue by dgilland** [marshmallow-code/webargs#9]
This feature would allow one to parse `None` values when they are explicitly sent in the request.

Currently, with `allow_missing=True`, sending a null value (e.g. over JSON) results in an empty parse.

Setting `allow_missing=False`, allows a null value through but does so even if the value wasn't actually sent in the request.

Something like `allow_none=True` would set `None` for the parameter but ONLY if it was included in the request.

My particular use case is in an API that allows partial updates to a database model. I need a way to send in `None` but only have it parsed if it's actually sent, e.g., `request.data={'param': None} => parsed={'params': None}` and `request.data={} => parsed={}`.

**Comment by sloria** [comment]
You raise a valid point. I'm thinking that the current behavior of `allow_missing=True` is incorrect when an argument is `None`. `None` should not be a special case; if it is explicitly included in the request, it should be included in the parsed arguments.

So perhaps the solution here is not an extra `allow_none` parameter but a modification to the behavior of the existing `allow_missing` parameter.

**Comment by sloria** [comment]
@dgilland OK, I've implemented the following behavior:
- If `allow_missing=True`, values will only be excluded if they are not found on the request.
- If `allow_missing=True` and a request argument is `None`, it will still be included in the parsed arguments.

Does this solve your problem?

**Comment by dgilland** [comment]
Yes it does. Thank you! :+1:
