### ISSUE TITLE
Field not validated when using Decimal(as_string=True)

### ISSUE THREAD

**Issue by davidthornton** [marshmallow-code/webargs#92]
When we do something like this

`'value': fields.Decimal(required=True, as_string=True),`

With this as input:

`{ "value": 123.2, ... }`

Webargs does not throw a 422 unprocessible entity error. We're using python flask, sqlalchemy and marshmallow, and we've looked all over at our code. Is it possible that this is an issue with webargs?

Thanks

**Comment by sloria** [comment]
`as_string` only affects serialization behavior, not validation/deserialization. See https://marshmallow.readthedocs.org/en/latest/api_reference.html#marshmallow.fields.Decimal . If you want to validate that the input must be a string, you could create a custom field that subclasses `marshmallow.fields.Decimal`.
