### ISSUE TITLE
Webargs 8 Question: Getting request data from 'data' instead of 'json'?

### ISSUE THREAD

**Issue by cherylchen2** [marshmallow-code/webargs#926]
In my current application, there are requests made where data is passed in the request as `data` instead of `json`:
```
request.put(
    url,
    data={"key": 1},
    header={}
)
```
But my controller fails to find these data unless I use `json` instead:
```
request.put(
    url,
    json={"key": 1},
    header={}
)
```

Is there no option to fetch information from `data` instead of `json`? Like `@use_kwargs(SomeSchema, location="data")` etc.

**Comment by sloria** [comment]
See the docs here on how to add a custom location https://webargs.readthedocs.io/en/latest/advanced.html#custom-location-handlers

**Comment by lafrech** [comment]
[This SO question](https://stackoverflow.com/questions/47188244/what-is-the-difference-between-the-data-and-json-named-arguments-with-reques) explains the difference between `data` and `json` in `requests`.

When using `data`, the payload is form-encoded, and the corresponding webargs location is `form`.

**Comment by sloria** [comment]
Ah right, I should have read the question more carefully. @lafrech is correct--use the form location to parse form-encoded data
