### ISSUE TITLE
use_kwargs documentation shows positional args

### ISSUE THREAD

**Issue by brettdh** [marshmallow-code/webargs#93]
Unless I am _very_ confused, the examples showing the use of the `@use_kwargs` decorator show it decorating functions with positional args; e.g.

``` python
@app.route('/echo', methods=['get', 'post'])
@parser.use_kwargs({'name': fields.Str()})
def greet(name):   # should be `def greet(name=None)` or something
    return 'Hello ' + name
```

I got very confused at first thinking that webargs must be doing some magic to make sure that the positional arguments get the right values based on their names. Though it was confusing, I followed the docs and tried to use `use_kwargs` with a lot of positional arguments, only to see errors like this:

```
TypeError: get_foo() takes exactly 8 non-keyword arguments (4 given)
```

If I make them all keyword args, they get the values I expect. So, I surmise that this is just a bug in the documentation - but then I see [unit tests](https://github.com/sloria/webargs/blob/pypi/tests/test_flaskparser.py#L288) using this syntax as well! And then there is the mysterious matter of those 4 positional arguments being passed - what are those, and how did they get in there? (For completeness: in my schema, two values are set in a `post_load` method, and two are `fields.Method` fields, so maybe that has something to do with it.)

Could you please clear this up?

**Comment by sloria** [comment]
`use_kwargs` simply deserializes request input data, then splats the resulting dictionary into the view (i.e. `**deserialized_data`. 

I'm not sure why you are seeing the error you are seeing. Can you post code to reproduce it?

**Comment by brettdh** [comment]
Oh wow, apparently there was a hole in my understanding of keyword args in Python - specifically, that they can be used to set positional arguments by name (second example [here](https://docs.python.org/2/tutorial/controlflow.html#keyword-arguments)).

Based on the timing of my initial post and some others that I posted, I suspect that this may have occurred during my confusion about `default`, `required`, and `missing` - i.e. perhaps I was using `default` for four of the parameters in the example above, resulting in them not being present in the dict that `use_kwargs` constructs.
