### ISSUE TITLE
The webargs has not the option webargs.fastapi

### ISSUE THREAD

**Issue by Kashif-Zeb** [marshmallow-code/webargs#975]
add this in the webargs.fastapi  to in webargs because  many ai project is coded in fastapi right now

**Comment by lafrech** [comment]
I don't see the point. AFAIK, FastAPI includes what webargs does. Why use webargs with FastAPI?

We could add support for Starlette, which FastAPI is built upon, but up till now, no one has ever stood up to contribute this feature.

**Comment by sirosen** [comment]
It's worth noting that Steven wrote a webargs-starlette package around when we/he (was I involved yet? Maybe not) decided that it's better to split support for each framework into a separate package. We should incorporate that work into webargs if we choose to reverse that decision. 

This issue gets a -1 from me, and I think we should close it as rejected. FastAPI uses pydantic for it's schemas -- it's in a different part of the ecosystem and that's okay.

**Comment by Kashif-Zeb** [comment]
Let say i pass the key id in params to get single data from db if using
webargs for this scenario it is easy to validate the key other wise
developer will use pydantic which is difficult and more lines of code same
case if developer use marshmallow  that why i suggest that add useagrs
functionality that support fastapi too

**Comment by lafrech** [comment]
> decided that it's better to split support for each framework into a separate package

I have a blur memory of this but I thought I got confused with apispec.

> We should incorporate that work into webargs if we choose to reverse that decision.

I would be easier to maintain webargs-starlette if it was included here, I suppose. But it would be a little more weight to maintain webargs. I don't care either way.

> This issue gets a -1 from me, and I think we should close it as rejected. FastAPI uses pydantic for it's schemas -- it's in a different part of the ecosystem and that's okay.

I give a +1 to your -1 for the same reason.

I don't know FastAPI but AFAIK it is meant to be used with Pydantic. If one wants to use marshmallow and webargs instead, then I guess webargs-starlette (+apispec) is the way to go.

https://github.com/sloria/webargs-starlette
